### ISSUE TITLE
[LM] Old Version showing up as latest in my Webbino library

### ISSUE THREAD

**Issue by SukkoPera** [arduino/library-registry#101]
I have recently deleted some bad old tags from my [Webbino](https://github.com/SukkoPera/Webbino) library. Please synchronize the [LIbrary Manager](https://www.arduino.cc/reference/en/libraries/webbino/).

In particular, version 20160709.0.0 should be deleted. This old version number exposes a sort of bug in the LM, as it will always show up as the latest version even though it's actually the oldest.

The latest version is now 0.9.97.

Also, the documentation link is outdated, as it points to a very old url (https://github.com/SukkoPera/Sukkino/tree/master/Webbino).

Thanks!

CC @gpb01

**Comment by per1234** [comment]
>Please synchronize the LIbrary Manager.

OK. Although the submission and indexing processes are automated, the removals and modifications are still manual processes. So it will be done on the next sweep by the index maintainer to clear all the outstanding requests.

>a sort of bug in the LM, as it will always show up as the latest version even though it's actually the oldest.

It's the newest according to semver:
https://semver.org/

>the documentation link is outdated, as it points to a very old url

This is likely coming from the 20160709.0.0 release's metadata, so will be fixed once the Library Manager index is synced.

**Comment by SukkoPera** [comment]
Yes, but that version number was given before semver was required/enforced. I think the .0.0 was added automatically, as I think I had just used the date (20160709). But never mind :).

Thanks a lot!

**Comment by per1234** [comment]
You're right that the `.0.0` will be added when only a major version number is provided in the library.properties `version` value.

semver still isn't required, and probably never will be, though it is encouraged. There is a required version format, which is a superset of semver called "relaxed semver":
https://github.com/bugst/relaxed-semver#semantic-versioning-specification-followed-in-this-library
The relaxed semver from the library's  library.properties `version` field is converted to true semver in the library release's `version` value store in [the Library Manager index](http://downloads.arduino.cc/libraries/library_index.json). It is that index that is used by the Arduino Library Manager and the generated library reference pages. So the semver sorting conventions can still be applied even when the source data is not true semver.

**Comment by cmaglie** [comment]
@SukkoPera there is a tag named `remove_panic_and_thermometer` that contains a library.properties with the version `20160709`, so even if I remove the release from the index, it will be fetched again!

https://github.com/SukkoPera/Webbino/blob/remove_panic_and_thermometer/library.properties

unfortunately, it's the library.properties that forces the version, whatever the git tag used.
Is this tag really needed? if no I would ask you to delete it so the indexer will not pick up that version of the library.

**Comment by SukkoPera** [comment]
Deleted, thanks for the notice!

**Comment by cmaglie** [comment]
Ok, the release has been removed.

**Comment by SukkoPera** [comment]
Thanks a lot, but the "bad" version still shows up [in the Library Reference Page](https://www.arduino.cc/reference/en/libraries/webbino/). Will it update automatically or does that need manual intervention too? Also the documentation link in that page is outdated.

**Comment by per1234** [comment]
Hi @SukkoPera. The library reference has now updated. The removed release is no longer shown and the "Read the documentation" link now points to the `url` value from the `0.9.97` release.

Please let us know if you have any questions or concerns.

**Comment by SukkoPera** [comment]
Thanks a lot!
