### ISSUE TITLE
Arduino Reference page not up to date

### ISSUE THREAD

**Issue by jpb10** [arduino/library-registry#1054]
I'm trying to figure out why the following [Arduino Reference page](https://www.arduino.cc/reference/en/libraries/solarcalculator/) is not up to date.

It shows up in Library Manager. Perhaps a cache issue?

Log:
>[...] 
2022/02/15 22:21:48 Checking out tag: v1.0.1
2022/02/15 22:21:48 Release SolarCalculator:1.0.1 already loaded, skipping
2022/02/15 22:21:48 Checking out tag: v1.0.2
2022/02/15 22:21:48 Release SolarCalculator:1.0.2 already loaded, skipping
2022/02/15 22:21:48 Checking out tag: v1.0.3
2022/02/15 22:21:48 Release SolarCalculator:1.0.3 already loaded, skipping

https://downloads.arduino.cc/libraries/logs/github.com/jpb10/SolarCalculator/

**Comment by Serjlee** [comment]
The job responsible for updating the reference was not running correctly, but it should now
