### ISSUE TITLE
Library name change request (dWin_Arduino --> dWin)

### ISSUE THREAD

**Issue by akkoyun** [arduino/library-registry#1112]
Hi friends,
I have a library registered as dWin_Arduino (https://github.com/akkoyun/dWin_Arduino)
i want to change this library name to https://github.com/akkoyun/dWin

i creare new release and change version update.

old name : dWin_Arduino
new name : dWin
new repo : https://github.com/akkoyun/dWin

**Comment by per1234** [comment]
Hi @akkoyun. The requested change is now in progress: https://github.com/arduino/library-registry/pull/1113, https://github.com/arduino/library-registry/pull/1114

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Should be solved by #1113 and #1114
