### ISSUE TITLE
Library name change request (MAX78630 Polyphase Energy Meter --> MAX78630)

### ISSUE THREAD

**Issue by akkoyun** [arduino/library-registry#1119]
Hi friends,
I have a library registered as "MAX78630 Polyphase Energy Meter" (https://github.com/akkoyun/MAX78630)
i want to change this library name to "MAX78630"

i creare new release and change version update.

old name : MAX78630 Polyphase Energy Meter
new name : MAX78630

**Comment by per1234** [comment]
Hi @akkoyun. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Should be solved
