### ISSUE TITLE
[Library manager] please add WizFi360 library

### ISSUE THREAD

**Issue by ekkai** [arduino/library-registry#112]
Please add the WizFi360 library found at https://github.com/ekkai/WizFi360 to the library manager.

**Comment by per1234** [comment]
Hi @ekkai. Thanks for your interest in contributing to the Arduino Library Manager index.

We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
