### ISSUE TITLE
[Library Manager] Please add Arduino-Scheduler library to the library manager

### ISSUE THREAD

**Issue by Robokishan** [arduino/library-registry#113]
hey I have developed a library and it is my first contribution to the opensource community.
Please add this arduino scheduler to the arduino library manager https://github.com/Robokishan/Arduino-Scheduler

**Comment by per1234** [comment]
Hi @Robokishan. The Library Manager indexer checks all the libraries on the list for new tags/releases hourly and adds any new release that is compliant with the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time.

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

We now provide a dedicated web page for each library that shows its indexer logs. You can see the logs for your library here:
https://downloads.arduino.cc/libraries/logs/github.com/Robokishan/Arduino-Scheduler/
(URL is based on the repository name at the time of the submission.

**Comment by Robokishan** [comment]
Oh thank you for the information. Great !
