### ISSUE TITLE
Library delete request

### ISSUE THREAD

**Issue by akkoyun** [arduino/library-registry#1140]
Hi,
I want to organize my libraries so I want to delete some of my libraries.

* https://github.com/akkoyun/GE910
* https://github.com/akkoyun/LinearRegression
* https://github.com/akkoyun/Battery
* https://github.com/akkoyun/B100AA
* https://github.com/akkoyun/B902AA

can u delete the libraries written above.

Thanks.

**Comment by per1234** [comment]
Hi @akkoyun. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when it is done. You will get a notification from GitHub at that time.

**Comment by umbynos** [comment]
Should be solved
