### ISSUE TITLE
Library delete request (https://github.com/akkoyun/I2C_Functions)

### ISSUE THREAD

**Issue by akkoyun** [arduino/library-registry#1150]
Hi,
Can u delete my library
https://github.com/akkoyun/I2C_Functions

thanks.

**Comment by per1234** [comment]
Hi @akkoyun. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when it is done. You will get a notification from GitHub at that time.

**Comment by akkoyun** [comment]
@per1234 can we cancel this request ?
i control for library manager everything is ok.

**Comment by per1234** [comment]
OK, the removal has now been canceled. The "I2C_Functions" library will remain in Library Manager.
