### ISSUE TITLE
Remove release: "EmotiBit FeatherWing"@1.3.30

### ISSUE THREAD

**Issue by nitin710** [arduino/library-registry#1165]
can this library be updated, please?
an older release 1.3.30 has been deleted and a newer release 1.3.31 has been added

**Comment by per1234** [comment]
Hi @nitin710. The Library Manager indexer checks all the libraries on the list for new tags/releases hourly and adds any new release that is compliant with [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list). So the library manager will automatically reflect your releases, with the exception those not found in the repository, which are preserved unless a formal [removal request](https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-remove-a-release-of-my-library-from-library-manager) was received.

We now provide a dedicated web page for each library that shows its indexer logs. You can see the logs for your library here:

https://downloads.arduino.cc/libraries/logs/github.com/EmotiBit/EmotiBit_FW_FeatherWing/

The new release has already been indexed successfully:

```text
2022/03/08 03:12:13 Checking out tag: v1.3.31
2022/03/08 03:12:13 Release EmotiBit FeatherWing:1.3.31 already loaded, skipping
```

After indexing, it may take some time for the updated index to propagate through the CDN and local caches to make your new release available everywhere, but it will get there in good time.

**Comment by nitin710** [comment]
@per1234 
i can still see `v1.3.30` as a possible version to download in the library manager in Arduino ide.
![image](https://user-images.githubusercontent.com/31810812/157250793-df18527b-9751-4740-a066-8b9f0f6ab812.png)

Is there any way to remove that version from the Arduino IDE as well?

**Comment by per1234** [comment]
I am confirming your request to have the 1.3.30 release of the library removed from the Arduino Library Manager index.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues when it is done. You will get a notification from GitHub at that time.

**Comment by umbynos** [comment]
Backend work done :tada:
```
2022/03/11 08:45:31 Loaded 4695 libraries from DB
Removing EmotiBit FeatherWing@1.3.30
Success!

```
