### ISSUE TITLE
[Library manager] Please add my library to the library manager

### ISSUE THREAD

**Issue by wollewald** [arduino/library-registry#1199]
Please add the following library (EEPROM_SPI_WE) to the Arduino library manager:

https://github.com/wollewald/EEPROM_SPI_WE

Great thanks in advance!

**Comment by per1234** [comment]
Hi @wollewald. Thanks for your interest in contributing to the Arduino Library Manager index.

We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
