### ISSUE TITLE
Library name change request (Moving Average Library --> Moving Average Plus)

### ISSUE THREAD

**Issue by AlexandreHiroyuki** [arduino/library-registry#1221]
Recently, I found a conflict with header file names on Arduino Editor Online. So I want to rename everything to avoid conflict with other libraries available in the manager.

I have a library registered as "Moving Average Library" (https://github.com/AlexandreHiroyuki/MovingAverage_ArduinoLibrary)
I want to change this library name to "Moving Average Plus"

The repository URL remains the same.

old name: Moving Average Library
new name: Moving Average Plus

**Comment by per1234** [comment]
Hi @AlexandreHiroyuki. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues and pull requests when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1226#issuecomment-1079110804
