### ISSUE TITLE
Library name change request - Remove spaces

### ISSUE THREAD

**Issue by AlexandreHiroyuki** [arduino/library-registry#1249]
I have a library registered as "Moving Average Library" (https://github.com/AlexandreHiroyuki/MovingAveragePlus)
I want to remove the spaces from the library name to "MovingAveragePlus".

The repository URL remains the same.

old name: Moving Average Plus
new name: MovingAveragePlus

**Comment by per1234** [comment]
Hi @AlexandreHiroyuki. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues and pull requests when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Should be resolved in #1248
