### ISSUE TITLE
[Library Manager] please add TSC2007 sensor library to the Arduino library manager

### ISSUE THREAD

**Issue by evaherrada** [arduino/library-registry#1255]
Please add this repository:
https://github.com/adafruit/Adafruit_TSC2007

Thanks!

**Comment by per1234** [comment]
Hi @evaherrada. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
