### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by dattasaurabh82** [arduino/library-registry#1449]
### Library name

RV8803Tiny

### Version to remove

0.0.7

**Comment by per1234** [comment]
Hi @dattasaurabh82. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues and pull requests when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by dattasaurabh82** [comment]
> 

So are we expecting 24 hrs (more or less)? 
and can I add the same tag again?

**Comment by per1234** [comment]
>So are we expecting 24 hrs (more or less)?

Probably more. As mentioned, this is a manual maintenance process which requires an operation on the backend database. Please be patient.

>can I add the same tag again?

You should use a different one (e.g., 0.0.8). It would be confusing to the users for there to be two different versions of the 0.0.7 release.

Development best practices are to never move a Git tag, as they are expected to be an immutable marker at a specific point in the repository history.

**Comment by umbynos** [comment]
Done
```
2022/05/31 08:15:13 Loaded 4902 libraries from DB
Removing RV8803Tiny@0.0.7
Success!
```
