### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by sz-coder** [arduino/library-registry#1463]
### Library repository URL

https://github.com/DuinoDNS/ddns-arduino-nightly-releases

**Comment by sz-coder** [comment]
I'd like this to be renamed to `ddns-nightly`. 

I wasn't aware that the name gets stored when added to the library-registery and had `ddns` as library name by mistake.

**Comment by per1234** [comment]
Hi @sz-coder. I apologize for my slow response (I was delayed in my duties by illness when your request came in).

I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by sz-coder** [comment]
Thank you so much! And no worries about the delayed response 😊

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1477#issuecomment-1154860718
