### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by brentru** [arduino/library-registry#1502]
### Library repository URL

https://github.com/adafruit/Adafruit_Wippersnapper_Arduino

**Comment by per1234** [comment]
Hi @brentru. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes the issues when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1503#issuecomment-1160190765
