### ISSUE TITLE
Delete the following two versions of the library

### ISSUE THREAD

**Issue by Mosiwi** [arduino/library-registry#1540]
### Library name

Mosiwi Basic Learning Kit

### Version to remove

- 1.0.0
- 2.1.1

**Comment by per1234** [comment]
I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by Mosiwi** [comment]
Hello, 9 days have passed, and the incorrect version information has not been cleared. Please help to clear them, thank you.

**Comment by umbynos** [comment]
Done:
```
2022/07/08 09:10:53 Loaded 4990 libraries from DB
Removing Mosiwi Basic Learning Kit@1.0.0
Success!
```
```
2022/07/08 09:11:02 Loaded 4990 libraries from DB
Removing Mosiwi Basic Learning Kit@2.1.1
Success!
```
