### ISSUE TITLE
Library name change request - M5Unit-EXTIO2

### ISSUE THREAD

**Issue by Tinyu-Zhao** [arduino/library-registry#1561]
### Library repository URL

https://github.com/m5stack/M5Unit-EXTIO2

**Comment by per1234** [comment]
Hi @Tinyu-Zhao. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by Tinyu-Zhao** [comment]
Ok, thank you for your help!

**Comment by umbynos** [comment]
Solved in https://github.com/arduino/library-registry/pull/1562#issuecomment-1178718986
