### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by angrest** [arduino/library-registry#1859]
### Library name

pocketBME280

### Version to remove

2.3.1 linked to v1.0.0 in my repository due to a copy-paste error in library.properties.

**Comment by per1234** [comment]
Hi @angrest. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done:
```
2022/09/27 12:55:13 Loaded 5177 libraries from DB
Removing pocketBME280@2.3.1
Success!
```
