### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by RLL-Blue-Dragon** [arduino/library-registry#1893]
### Library repository URL

https://github.com/RLL-Blue-Dragon/OSS-EC_NXP_MPXA4250A_00000057

**Comment by RLL-Blue-Dragon** [comment]
Rename
Before) https://github.com/RLL-Blue-Dragon/NXP_MPXA4250A_00000057
after) https://github.com/RLL-Blue-Dragon/OSS-EC_NXP_MPXA4250A_00000057

**Comment by per1234** [comment]
Hi @RLL-Blue-Dragon. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1885#issuecomment-1259455512

**Comment by RLL-Blue-Dragon** [comment]
Thank you!
