### ISSUE TITLE
library.properties not found even if it is and in UTF-8

### ISSUE THREAD

**Issue by Nilon123456789** [arduino/library-registry#1969]
### Describe the problem

I'm trying to publish my [library](https://github.com/Nilon123456789/Receiver) but I keep getting the error library.properties not found but it is present in the root of my git repo

### To reproduce

Try to publish this library with a push request : https://github.com/Nilon123456789/Receiver

### Expected behavior

Get the error : `ERROR: Library is missing a library.properties metadata file.`

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hello @Nilon123456789. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Nilon123456789/Receiver/tree/v1.0.0

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment on the pull request to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Nilon123456789** [comment]
Maybe update the error message of the ArduinoBot to specify to remake the release and a new tag. Because I didn't find any mention of that in the FAQ nor in the documentation

**Comment by per1234** [comment]
The comment from a bot includes this:

>More information:
https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

If you visit that link you will see this:

>#### If the problem is with the library:
>
>1. Make the necessary fix in the library repository.
>1. Increment the `version` value in the library's [library.properties file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).
>1. Create a [release](https://docs.github.com/repositories/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag). The Library Manager index always uses tagged versions of the libraries, so even if the development version of the library is compliant, it can't be accepted until the latest release or tagis compliant. Alternatively, you can redo the existing release/tag if you prefer.
>1. Comment on your pull request here in the `arduino/library-registry` repository, mentioning **@ArduinoBot** in the comment. Doing this will cause the automated check to run again.
