### ISSUE TITLE
Library name change request: Makerlabvn_I2C_Motor_Driver

### ISSUE THREAD

**Issue by makerlabvn** [arduino/library-registry#1975]
### Library repository URL

https://github.com/makerlabvn/Makerlabvn_I2C_Motor_Driver

**Comment by makerlabvn** [comment]
Please help me change the name to "Makerlabvn_I2C_Motor_Driver"
![image](https://user-images.githubusercontent.com/40706910/195525994-4ce218a1-072d-4931-b3b6-595fe7aca507.png)

Thank you very much!

**Comment by per1234** [comment]
Hi @makerlabvn. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by makerlabvn** [comment]
> Hi @makerlabvn. I am confirming your request.
> 
> Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.
> 
> After that, you can monitor the indexing of the library via its dedicated logs web page. Information about that here: https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

Thank you for your confirmation!

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1976#issuecomment-1288857809
