### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by akhil-pa05** [arduino/library-registry#1996]
### Library repository URL

https://github.com/Travancore-Analytics/iot-suite

**Comment by per1234** [comment]
Hi @akhil-pa05. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by akhil-pa05** [comment]
> Hi @akhil-pa05. I am confirming your request.
> 
> Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.
> 
> After that, you can monitor the indexing of the library via its dedicated logs web page. Information about that here: https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

Hi @per1234,
Is any way that you can make this merge as early as possible, since this is not just a rename change but fixed a typo mistake in the dependent library list. Because of that, none will able to install the library. Since this incorrect dependent library name was also part of initial version, chances for someone to install this library is none.

So could you able help to make this merge to complete sooner?

**Comment by per1234** [comment]
Hi @akhil-pa05. Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done.

So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You can follow the issue/PRs to receive a notification from GitHub when it is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

We'll surely get to it soon, please be patient.

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/1997#issuecomment-1288856085
