### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by hung-eoh** [arduino/library-registry#2025]
### Library repository URL
Companion to #2024 
It is currently listed in the Library Manager as:

```
EoH Platform
https://github.com/eoh-jsc/mvp-lib
```

It is now:

```
ERa
https://github.com/eoh-jsc/era-lib
```

Please kindly update the Arduino library manager master list. Thank you.

**Comment by per1234** [comment]
Hi @hung-eoh. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/2026#issuecomment-1308493649
