### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by zeynepdicle** [arduino/library-registry#2170]
### Library repository URL

https://github.com/deneyapkart/deneyap-gercek-zamanli-saat-arduino-library

**Comment by per1234** [comment]
Hi @zeynepdicle. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by zeynepdicle** [comment]
Hi @per1234 normally Arduino libraries will be updated one day. But my name has changed from "Deneyap Gercek Zamanli Saat MCP7940" to "Deneyap Gercek Zamanli Saat" and I can't see the update.

**Comment by per1234** [comment]
Hi @zeynepdicle. Unlike submissions and releases, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done.

That may take a couple of weeks.

If you are subscribed to this issue, you will receive a notification from GitHub when it is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

**Comment by zeynepdicle** [comment]
> Hi @zeynepdicle. Unlike submissions and releases, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done.
> 
> That may take a couple of weeks.
> 
> If you are subscribed to this issue, you will receive a notification from GitHub when it is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

My library new release doesn't update in Arduino. Is having error ? if have a error what is this ?

**Comment by per1234** [comment]
@zeynepdicle you should always check the dedicated logs web page for your library when you notice a release was not added to Library Manager. The URL of that page was provided when you submitted your library:

https://github.com/arduino/library-registry/pull/1549

>You can check the logs from the Library Manager indexer for your library(s) here:
>http://downloads.arduino.cc/libraries/logs/github.com/deneyapkart/deneyap-kizilotesi-alici-verici-arduino-library/
>http://downloads.arduino.cc/libraries/logs/github.com/deneyapkart/deneyap-gercek-zamanli-saat-arduino-library/

The reason the release was rejected is shown clearly in those logs:

>2022/12/05 07:25:01 Checking out tag: 1.0.1
>2022/12/05 07:25:01 Release Deneyap Gercek Zamanli Saat:1.0.1 has wrong library name, should be Deneyap Gercek Zamanli Saat MCP7940

**Comment by zeynepdicle** [comment]
@per1234 yes, I know the name of my library.
 I created these issues because I wanted to change the library name from "Deneyap Gercek Zamanli Saat MCP7940" to "Deneyap Gercek Zamanli Saat".

**Comment by per1234** [comment]
>I created these issues because I wanted to change the library name

Obviously.

What should also be obvious is that releases made with the "Deneyap Gercek Zamanli Saat" name value will be rejected until that name change is complete.

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/2176#issuecomment-1346873180
