### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by einspunktnull** [arduino/library-registry#2284]
### Library name

DualSenseController

### Version to remove

1.0.0

**Comment by per1234** [comment]
Hi @einspunktnull. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done:
```
2022/12/22 11:07:12 Loaded 5440 libraries from DB
Removing DualSenseController@1.0.0
Success!
```
