### ISSUE TITLE
Please add the library for DRV8833 Motor Driver

### ISSUE THREAD

**Issue by bhosaletejas03** [arduino/library-registry#2334]
Can you please add the library for DRV8833 Motor Driver.

GitHub link:  [https://github.com/bhosaletejas03/DRV8833_Motor_Driver](url)

https://github.com/bhosaletejas03/DRV8833_Motor_Driver.git

Many Thanks.

**Comment by per1234** [comment]
Hi @bhosaletejas03. We have a new system for submitting libraries. The instructions are here:

https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
