### ISSUE TITLE
Is this repository also for Board Support packages?

### ISSUE THREAD

**Issue by dwillmore** [arduino/library-registry#2371]
### Describe the problem

We have a board support package and would like it to be part of the boards available in the Arduino IDE UI

### To reproduce

This does not seem relevant to my question.

### Expected behavior

To be able to add a link to our json file adding support for our project.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @dwillmore. This registry is only for Arduino libraries.

Arduino only adds the official boards platforms and those of their business partners to the primary package index that is listed by default in Arduino IDE. 3rd party platforms must be added via the "Additional Boards Manager URLs" field in the IDE preferences.

There is a community maintained list of these 3rd party package index URLs in the Arduino GitHub Wiki:

https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

You are very welcome to add your URL to that list. The wiki is publicly editable, so you can just click the "**Edit**" button on that page and add it right in.

Please let me know if you have any questions.

Regards,
Per

**Comment by dwillmore** [comment]
Wonderful, thank you for your help.
