### ISSUE TITLE
[Library Manager] Please add mimuz-ch55x library

### ISSUE THREAD

**Issue by tadfmac** [arduino/library-registry#2372]
Hello.

I created a library to addition simple MIDI comminucation to ch55xduino core.
Could you add this to a list of libraries?

url: https://github.com/mimuz/mimuz-ch55x

Thanks.

**Comment by per1234** [comment]
Hi @tadfmac. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per

**Comment by tadfmac** [comment]
Thank's your support!
