### ISSUE TITLE
Remove spurious releases of "PID"

### ISSUE THREAD

**Issue by per1234** [arduino/library-registry#238]
While doing some maintenance on the registry data file, I discovered that two libraries with the same name "PID" had been added to the registry at some point and the index contains a combination of the two library's releases under that name.

The name of one of the two has since been updated to "ArcPID" by the library author:
https://github.com/ettoreleandrotognoli/ArcPID/blob/0.0.3/library.properties#L1
and its registry entry updated accordingly:
https://github.com/arduino/library-registry/pull/235/commits/1e608516285b47182f0c90d23c786a71325f934f
its releases under that name will be added to the index.

The "PID" library releases should be restricted to those of the remaining library of that name, as listed here:
https://github.com/br3ttb/Arduino-PID-Library/tags

So please remove these releases from the index:

- PID@0.0.1
- PID@0.0.2

**Comment by rsora** [comment]
After the surgery operations crawler side now we have:

```
$ arduino-cli lib search "PID"                                                                                                                                      
Updating index: library_index.json downloaded                                                                                                                        
Name: "ArcPID"
  Author: Ettore Leandro Tognoli
  Maintainer: Ettore Leandro Tognoli - ettore.leandro.tognoli@gmail.com
  Sentence: PID controller
  Paragraph: A library to calculate PID which has low coupling with IO
  Website: https://github.com/ettoreleandrotognoli/ArcPID
  Category: Device Control
  Architecture: *
  Types: Contributed
  Versions: [0.0.3]
[...]
Name: "PID"
  Author: Brett Beauregard
  Maintainer: Brett Beauregard
  Sentence: PID controller
  Paragraph: A PID controller seeks to keep some input variable close to a desired setpoint by adjusting an output. The way in which it does this can be 'tuned' by adjusting three parameters (P,I,D).
  Website: http://playground.arduino.cc/Code/PIDLibrary
  Category: Signal Input/Output
  Architecture: *
  Types: Contributed
  Versions: [1.1.1, 1.2.0]
[...]
```

So releases should be correctly listed for each library.

Happy coding!
