### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by Vi-Ku** [arduino/library-registry#2435]
### Library repository URL

https://github.com/mission-mangal/SpeedControl

**Comment by Vi-Ku** [comment]
i would like to change the name of the library as there are warning associated with the name of the library i have created. so i have created the specific release of the library with change in the name and a new relase of the same too.

**Comment by per1234** [comment]
Hi @Vi-Ku. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/02/01 15:53:02 Loaded 5528 libraries from DB
Removing Speed Control
Success!
```
