### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by teruyamato0731** [arduino/library-registry#2437]
### Library name

Chassis

### Version to remove

1.2.6-ci.0

**Comment by per1234** [comment]
Hi @teruyamato0731. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/02/01 15:50:50 Loaded 5528 libraries from DB
Removing Chassis@1.2.6-ci.0
Success!
```
