### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by aentinger** [arduino/library-registry#2548]
### Library repository URL

https://github.com/facchinm/USBHostMbed5

**Comment by aentinger** [comment]
This library has been previously added to the library manager [here](https://github.com/arduino/library-registry/pull/2538/files) due to pressing concerns related to the release of the Arduino Giga.

However, since it has since become an official Arduino library a name change (incl a repository owner change) has become necessary. Consequently it is also necessary to update its URL.

**Comment by per1234** [comment]
Hi @aentinger. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/03/15 14:54:22 Loaded 5626 libraries from DB
Removing USBHostMbed5
Success!
```
