### ISSUE TITLE
Some code is not updated after the library update

### ISSUE THREAD

**Issue by STONElibrary** [arduino/library-registry#2563]
### Describe the problem

Hello, in my newly released v.1.1.0 release of the Stone_serial library, the library downloaded in the IDE is different from the library in my distribution

### To reproduce

https://github.com/STONElibrary/arduino_lib/releases/tag/v1.1.0
For example, the stone_receive_group.cpp file that I downloaded from this link contains V1.1.0 characters, but the stone_receive_group.cpp file that I downloaded from the IDE contains V1.0.9 characters

### Expected behavior

I hope you can make the library files you search for in your IDE exactly the same as those in your distribution

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
@STONElibrary don't you think it would have been helpful to mention in your report that you made a bad 1.1.0 release and then later retagged?

I already explained in your release removal request of three days ago that you need to wait for a maintainer to make the removal:

https://github.com/arduino/library-registry/issues/2545#issuecomment-1461537689

Until that is done, it is expected that the bad release will still be in Arduino Library Manager.

My recommendation is for you to make a new release (e.g., 1.1.1). That is much more friendly to the users than creating multiple variants with the same version number.
