### ISSUE TITLE
[Library manager] Request to add library

### ISSUE THREAD

**Issue by cparata** [arduino/library-registry#259]
Hi,
could you please add the following library to the Library Manager?

https://github.com/stm32duino/X-NUCLEO-IHM01A1

Best Regards,
Carlo

**Comment by per1234** [comment]
Hi @cparata. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
