### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by Nilon123456789** [arduino/library-registry#2623]
### Library repository URL

https://github.com/Nilon123456789/Firmetix-Library

**Comment by Nilon123456789** [comment]
I want to change the name of the library from Firmetix4Arduino to only Firmetix since now the library also supports esp32 and esp8266 so the name Firmetix4Arduino is not matching anymore

**Comment by per1234** [comment]
Hi @Nilon123456789. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/03/29 15:36:32 Loaded 5663 libraries from DB
Removing Firmetix4Arduino
Success!
```
