### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by RoanBrand** [arduino/library-registry#2626]
### Library repository URL

https://github.com/RoanBrand/ArduinoSerialToTCPBridgeClient

**Comment by RoanBrand** [comment]
This is a old 3rd party lib with name the [ArduinoSerialToTCPBridgeClient](https://github.com/RoanBrand/ArduinoSerialToTCPBridgeClient)

According to the docs, new libs may not have `Arduino` as a prefix in the name.
It seems old libraries already listed in the Library Manager won't get updated with a new release, probably until the name is changed too.

I changed the name to `TCP over Serial`, and made other changes to satisfy `arduino-lint`, but left the repository's name the same.

Please let me know if there are any issues.

**Comment by per1234** [comment]
Hi @RoanBrand. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/03/29 15:40:00 Loaded 5662 libraries from DB
Removing ArduinoSerialToTCPBridgeClient
Success!
```
