### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by gilman88** [arduino/library-registry#2659]
### Library repository URL

https://github.com/gilman88/xmodem-lib

**Comment by gilman88** [comment]
Hi I misunderstood the name metadata value in the properties file and thought it was supposed to be a human readable title instead of the name of the main library class folder. So after seeing the linter warnings I created a new release that addressed them

**Comment by per1234** [comment]
Hi @gilman88. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by gilman88** [comment]
Thanks for the confirmation @per1234

**Comment by MatteoPologruto** [comment]
Done:
```
2023/04/12 15:49:15 Loaded 5692 libraries from DB
Removing XModem transfer library
Success!
```
