### ISSUE TITLE
Remove "UltraDistSensor@1.0.0" release

### ISSUE THREAD

**Issue by per1234** [arduino/library-registry#284]
For details, see:
https://github.com/arduino/library-registry/pull/278

The issue was specific to the 1.0.0 release of the library. That tag has been removed from the library repository and a new 1.1.0 release made that does not have the issue. So it is now only necessary to remove the problematic 1.0.0 release from the Library Manager index and all will be well.

**Comment by rsora** [comment]
Release `1.0.0` is now removed:

```
$ arduino-cli lib search "UltraDistSensor"         
Updating index: library_index.json downloaded                                   
Name: "UltraDistSensor"
  Author: Shubham Trivedi
  Maintainer: Shubham Trivedi shubhamtrivedi95@gmail.com
  Sentence: Interface the HC-SR04 sensor and ping sensor to Arduino.
  Paragraph: The UltraDistSensor library has been developed to allow HC-SR04 sensor and ping sensor to communication with arduino board. This library can be used to interface multiple sensors.
  Website: https://github.com/shubhamtivedi95/UltraDistSensor
  Category: Sensors
  Architecture: *
  Types: Contributed
  Versions: [1.1.0]
``` 

As you can see only version `1.1.0` is shown in the Library Manager

Happy coding!
