### ISSUE TITLE
[Library Manager] Request to add new library

### ISSUE THREAD

**Issue by GhassanYusuf** [arduino/library-registry#2845]
Dear Arduino Platform Community, 

I would like to request to add my library to Arduino IDE

The Github Repository
[https://github.com/GhassanYusuf/NewServo](https://github.com/GhassanYusuf/NewServo)

Library Properties File
[https://github.com/GhassanYusuf/NewServo/blob/main/library.properties](https://github.com/GhassanYusuf/NewServo/blob/main/library.properties)

**Comment by per1234** [comment]
Hi @GhassanYusuf. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
