### ISSUE TITLE
RaiseDev new library releases are not picked up

### ISSUE THREAD

**Issue by MikeMcQuaid** [arduino/library-registry#2867]
### Describe the problem

The indexer logs show 0.0.6 as the latest version (https://downloads.arduino.cc/libraries/logs/github.com/raisedevs/raise-dev-library/) but an install/upgrade shows 0.0.4 as the latest version

### To reproduce

`arduino-cli lib install RaiseDev`, note 0.0.4 is installed and not 0.0.6.

### Expected behavior

`arduino-cli lib install RaiseDev` installs 0.0.6.

### Additional context

- 0.0.3 failed linting
- 0.0.5 still had 0.0.4 as the version in `library.properties`

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @MikeMcQuaid. I was not able to reproduce the fault:

```text
$ arduino-cli version
arduino-cli.exe  Version: 0.32.2 Commit: 2661f5d9 Date: 2023-04-12T09:41:59Z

$ arduino-cli lib install RaiseDev
Downloading index: library_index.tar.bz2 downloaded
Downloading RaiseDev@0.0.7...
RaiseDev@0.0.7 downloaded
Installing RaiseDev@0.0.7...
Installed RaiseDev@0.0.7
```

This might be caused by you having an outdated version of the Library Manager index on your computer. Please try updating the index by running this command:

```text
arduino-cli lib update-index
```

After that, try installing the library again. It should install the latest release (0.0.7) this time.

**Comment by MikeMcQuaid** [comment]
Thanks for trying to reproduce. I think I resolved this myself by removing some bad tags and pushing another release. Sorry to waste your time and thanks for your contributions to open source, they are much appreciated 🙇‍♂️
