### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by Nilon123456789** [arduino/library-registry#2910]
### Library name

Firmetix

### Version to remove

7.1.0

**Comment by per1234** [comment]
Hi @Nilon123456789. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by Nilon123456789** [comment]
I was wondering witch url should I use to see the logs of my library. I tried those two links and none of them is working. Im I doing something wrong?
 
https://downloads.arduino.cc/libraries/logs/github.com/nilon123456789/firmetix-library/
https://downloads.arduino.cc/libraries/logs/github.com/nilon123456789/firmetix/

**Comment by per1234** [comment]
The logs web page URL is based on the repository URL:

https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

> ```
> http://downloads.arduino.cc/libraries/logs/<host>/<repository slug>/
> ```

So this library's logs are here:

https://downloads.arduino.cc/libraries/logs/github.com/Nilon123456789/Firmetix-Library/

(note the path is case sensitive)
