### ISSUE TITLE
TinyMegaI2C & RV8803Tiny still not loaded to latest versions

### ISSUE THREAD

**Issue by dattasaurabh82** [arduino/library-registry#294]
[https://github.com/dattasaurabh82/TinyMegaI2C](https://github.com/dattasaurabh82/TinyMegaI2C)
[https://github.com/dattasaurabh82/RV8803Tiny](https://github.com/dattasaurabh82/RV8803Tiny)

These two libraries are still not loaded. 
As highlighted earlier, I fixed the properties and pushed again and it has been also more than 48 hours.

Am I still miss something? 🤔

```
2021/07/29 05:59:37 Scraping https://github.com/dattasaurabh82/TinyMegaI2C.git
2021/07/29 05:59:37 Checking out tag: 0.0.1
2021/07/29 05:59:37 Release TinyMegaI2C:0.0.1 already loaded, skipping
2021/07/29 05:59:37 Checking out tag: 0.0.2
2021/07/29 05:59:38 Release TinyMegaI2C:0.0.1 already loaded, skipping

```

```
2021/07/29 05:59:37 Scraping https://github.com/dattasaurabh82/RV8803Tiny.git
2021/07/29 05:59:38 Checking out tag: 0.0.1
2021/07/29 05:59:38 Release RV8803Tiny:0.0.1 already loaded, skipping
2021/07/29 05:59:38 Checking out tag: 0.0.2
2021/07/29 05:59:38 Release RV8803Tiny:0.0.2 already loaded, skipping
2021/07/29 05:59:38 Checking out tag: 0.0.3
2021/07/29 05:59:38 Release RV8803Tiny:0.0.2 already loaded, skipping
```

**Comment by per1234** [comment]
Library Manager works exclusively from Git tags, so the bot checks out the tags of the repository and, even though you have updated it after the fact, at the time of the tag the `version` value was incorrect just as it was the first time you reported this (https://github.com/arduino/library-registry/issues/286):

- https://github.com/dattasaurabh82/TinyMegaI2C/blob/0.0.2/library.properties#L2
- https://github.com/dattasaurabh82/RV8803Tiny/blob/0.0.3/library.properties#L2

Here's what you need to do:

1. Bump the `version` value in library.properties.
2. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
