### ISSUE TITLE
Library name change request from ESP8266SAM to ESP8266SAM_ES

### ISSUE THREAD

**Issue by pablomarquez76** [arduino/library-registry#2974]
### Library repository URL

https://github.com/pablomarquez76/ESP8266SAM_ES

**Comment by pablomarquez76** [comment]
This library must change its name since is the same as the original SAM library, but the reciter of this library was completely modified to recite in Spanish language.

**Comment by per1234** [comment]
Hi @pablomarquez76. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/06/27 15:47:26 Loaded 5949 libraries from DB
Removing ESP8266SAM
Success!
```
