### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by lukeclements** [arduino/library-registry#2986]
### Library name

artemis-cubesat

### Version to remove

- `1.0`
- `1.1`
- `1.2`
- `1.3`
- `1.4`
- `1.5`
- `1.6`

**Comment by per1234** [comment]
Hi @lukeclements. You must delete the [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) from the library's GitHub repository before we can remove the releases. I see that they have not yet been removed:

https://github.com/hsfl/artemis-cubesat/tags

I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/hsfl/artemis-cubesat/releases/tag/v1.0
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Repeat the above steps for the tags of each of the other releases you are requesting be removed.
1. Comment here to let me know that the tags have been deleted so that I can proceed with removing the releases from Arduino Library Manager.

**Comment by lukeclements** [comment]
Hi, sorry about that. I have deleted the tags.

**Comment by per1234** [comment]
I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Hello @lukeclements, I tried removing the releases you mentioned but the operation failed for each one with this message:
```
Removing artemis-cubesat@1.0
error: Library release artemis-cubesat@1.0 not found
Original files were restored.
```
I see that the repository https://github.com/hsfl/artemis-cubesat/releases has no releases and this might be the reason why they cannot be found inside the database. Could you please double check that every information you provided is correct?
In case everything is correct, the fact that the releases are not contained in the database could be a valid reason to mark this issue as resolved. What do you think @per1234?

Sorry for the inconvenience.

**Comment by lukeclements** [comment]
Yes, sorry that makes sense. There is not a version 1.0 which is an error on my end.

**Comment by MatteoPologruto** [comment]
For the sake of transparency, here are the results of each other removal attempt:
```
2023/07/06 08:44:41 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.1
error: Library release artemis-cubesat@1.1 not found
Original files were restored.
```
```
2023/07/06 08:44:47 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.2
error: Library release artemis-cubesat@1.2 not found
Original files were restored.
```
```
2023/07/06 08:44:51 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.3
error: Library release artemis-cubesat@1.3 not found
Original files were restored.
```
```
2023/07/06 08:44:56 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.4
error: Library release artemis-cubesat@1.4 not found
Original files were restored.
```
```
2023/07/06 08:45:01 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.5
error: Library release artemis-cubesat@1.5 not found
Original files were restored.
```
```
2023/07/06 08:45:06 Loaded 5962 libraries from DB
Removing artemis-cubesat@1.6
error: Library release artemis-cubesat@1.6 not found
Original files were restored.
```
Since no release is actually present in the database, I will close this issue and mark it as resolved.
Thanks for your patience!

**Comment by lukeclements** [comment]
Hi, thank you for your assistance. When I view the library from Arduino IDE 2.0 I still see that the library has 1.1.0, 1.2.0, 1.3.0, and 1.4.0 still listed. 
<img width="452" alt="Screenshot 2023-07-06 at 1 44 08 PM" src="https://github.com/arduino/library-registry/assets/54648672/7858f187-539d-40d7-bf04-508ce6ecc1f8">

**Comment by MatteoPologruto** [comment]
Done:
```
2023/07/07 07:37:32 Loaded 5963 libraries from DB
Removing artemis-cubesat@1.1.0
Success!
```
```
2023/07/07 07:37:40 Loaded 5963 libraries from DB
Removing artemis-cubesat@1.2.0
Success!
```
```
2023/07/07 07:37:46 Loaded 5963 libraries from DB
Removing artemis-cubesat@1.3.0
Success!
```
```
2023/07/07 07:37:53 Loaded 5963 libraries from DB
Removing artemis-cubesat@1.4.0
Success!
```
```
2023/07/07 07:38:00 Loaded 5963 libraries from DB
Removing artemis-cubesat@1.5.0
Success!
```
