### ISSUE TITLE
Add KCN Utility Lib

### ISSUE THREAD

**Issue by KCN-judu** [arduino/library-registry#3026]
Hello : )
Could u plz add this lib to the lib manager?
https://github.com/KCN-judu/KCN-Utility-Arduino-lib

Thanks!

**Comment by per1234** [comment]
Hi @KCN-judu. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per

**Comment by KCN-judu** [comment]
thanks
