### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by Rupakpoddar** [arduino/library-registry#3127]
### Library repository URL

https://github.com/Rupakpoddar/ESP8266Webhook

**Comment by per1234** [comment]
Hi @Rupakpoddar. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by Rupakpoddar** [comment]
Hi @per1234 -- I was wondering how long it usually takes to handle these requests? Thank you.

**Comment by per1234** [comment]
There is no set schedule. They are handled in batches as the database maintainer finds time. We carefully track the requests so we'll be certain not to forget yours. Please be patient.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/14 08:52:01 Loaded 6089 libraries from DB
Removing ESP8266 Webhooks
Success!
```
