### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by nthnn** [arduino/library-registry#3172]
### Library repository URL

https://github.com/nthnn/TCS3200

**Comment by per1234** [comment]
Hi @nthnn. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
@nthnn we need to leave this open until the database maintainer has accommodated your request.

Please understand that, although submissions are handled by an automated system, all other requests such as this name change are handled by humans. So if something is not clear to you or if you have some concern, then you can communicate that in a human manner and we will respond.

**Comment by nthnn** [comment]
The library manager seems to have updated my submission. I think I can close this now.

**Comment by per1234** [comment]
@nthnn I'll say it again: LEAVE THE ISSUE OPEN!!! You are being very disrespectful by wasting my time with this behavior.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/14 09:03:52 Loaded 6087 libraries from DB
Removing TCS3200
Success!
```
