### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by AlexRosito67** [arduino/library-registry#3175]
### Library repository URL

https://github.com/AlexRosito67/QUAD7SHIFT

**Comment by per1234** [comment]
Hi @AlexRosito67. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by AlexRosito67** [comment]
Please help me change my library's name from FSSD to QUAD7SHIFT. Here are the reasons I think the name should change:
The problem is that my library was called FSSD and it might have a name that can confuse the potential user about the purpose of my library. I, then, decided to change its name to QUAD7SHIFT (Four seven segment displays with shift registers, not a great name either but I'm not too imaginative). But even though I could change the name it seems that in your side you are still getting the library.properties with the information of the FSSD library that, by the way,  lacks of the correct url which has an * and not "https://github.com/AlexRosito67/QUAD7SHIFT". 
Thank you so much for your help.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/14 09:06:03 Loaded 6086 libraries from DB
Removing FSSD
Success!
```
