### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by stlljonas** [arduino/library-registry#3178]
### Library repository URL

https://github.com/sensirion/arduino-i2c-svm4x

**Comment by per1234** [comment]
Hi @stlljonas. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by stlljonas** [comment]
Just for additional info: This is a follow up from issue #2994, where this library got its url changed. In the accompanying issue #2968 it was noted that this name changing step also needs to be performed.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/14 09:07:45 Loaded 6085 libraries from DB
Removing Sensirion I2C SVM41
Success!
```
