### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by epsilonrt** [arduino/library-registry#3195]
### Library repository URL

https://github.com/epsilonrt/pimp

**Comment by epsilonrt** [comment]
this library has been renamed, the new repository is https://github.com/epsilonrt/pImpl

**Comment by per1234** [comment]
Hi @epsilonrt. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/08/14 09:11:43 Loaded 6084 libraries from DB
Removing pimp
Success!
```
