### ISSUE TITLE
Add  TinyGPSPlus library

### ISSUE THREAD

**Issue by Tinyu-Zhao** [arduino/library-registry#330]
Hi
Could you please add this library to the library manager?
https://github.com/Tinyu-Zhao/TinyGPSPlus

**Comment by per1234** [comment]
Hi @Tinyu-Zhao. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
