### ISSUE TITLE
AAAchiyukeji_zong libraries

### ISSUE THREAD

**Issue by yirujikeshenshihao** [arduino/library-registry#3317]
https://github.com/yirujikeshenshihao/AAAchiyukeji_zong

Please add my library to the manager, which collects commonly used module usage and basic standard program framework, as well as some commonly used filtering algorithms, which can reduce repetitive workload

Thank you

**Comment by per1234** [comment]
Hi @yirujikeshenshihao. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
