### ISSUE TITLE
Add Honeywell_SPI_FMA library to Arduino Library Manager

### ISSUE THREAD

**Issue by JayasinghePasan** [arduino/library-registry#3337]
**Library Name**: Honeywell_SPI_FMA

**Description**: A library for easy use of the Honeywell FMA series SPI force sensors with Arduino. 

**Suported Sensors**: FMAMSDXX025WCSC3, FMAMSDXX015WCSC3, FMAMSDXX005WCSC3

**Library Repository**: [https://github.com/JayasinghePasan/Honeywell_SPI_FMA](#) 

**Documentation Links**:
- [Sensor Data Sheet](https://sps.honeywell.com/gb/en/products/advanced-sensing-technologies/healthcare-sensing/force-sensors/microforce-fma-series)

I kindly request the addition of this library to the Arduino Library Manager. Thanks for considering!

**Comment by per1234** [comment]
Hi @JayasinghePasan. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
