### ISSUE TITLE
nonblocking timer library

### ISSUE THREAD

**Issue by richardsibanda** [arduino/library-registry#3399]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
i would like to have my library included in arduino library manager.
with below link
 [https://github.com/richardsibanda/nonblockingtimer](link)

**Comment by per1234** [comment]
I see you found the correct way to submit libraries and have already made a successful submission (https://github.com/arduino/library-registry/pull/3397) so I'll close this as resolved.
