### ISSUE TITLE
 [Library Manager] Please add library ESP32WebRemoteControl

### ISSUE THREAD

**Issue by madhephaestus** [arduino/library-registry#3425]
Can you please add:

https://github.com/madhephaestus/ESP32WebRemoteControl

To the library manager? 

It provides a fast, low latency RC control via web sockets on the ESP32. 

Thank you!

**Comment by per1234** [comment]
Hi @madhephaestus. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per

**Comment by madhephaestus** [comment]
@per1234 Oh, thank you for the heads up. I moved it over to: https://github.com/arduino/library-registry/pull/3426
