### ISSUE TITLE
What to do about my problems with the library?

### ISSUE THREAD

**Issue by RodrigoDornelles** [arduino/library-registry#3428]
### Library repository URL
https://github.com/rodrigodornelles/3bc-lang

I built the [`3bc-language-virtual-machine`](https://reference.arduino.cc/reference/en/libraries/3bc-language-virtual-machine/) library and I have two problems with it.

 * I would like to remove version `0.0.1` without deleting it from my github releases.
   * _thought when publish the most recent version but when I posted and not the retrogrades,<br/>in this case this 0.0.1 is just a draft that doesn't work._
 * I would like to rename it to `3bc-lang` only.
 
Perhaps the ideal would be to delete the package completely from the registry, this year I still intend to release a `0.2` version with other interfaces.

I'm not sure what to do, I don't care if versions `0.1.1`, `0.1.2`, and `0.1.3` disappear.

**Comment by per1234** [comment]
Hi @RodrigoDornelles. The Library Manager indexer system ignores any release that has a value in the `name` field of the `library.properties` metadata file that doesn't match the registered library name.

This means that if you request the name change to `3bc-lang`, all previous releases that had the previously registered `3BC Language Virtual Machine` name in the metadata will be removed from the Library Manager index.

This means you can accomplish both your stated goals in one operation.

Instructions for requesting a name change are available here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name
