### ISSUE TITLE
Change "I2C Helper" library name

### ISSUE THREAD

**Issue by Basirk** [arduino/library-registry#346]
Hi,

Please can you change my library name?
It is currently "I2C Helper", but I removed the space as per the lint warning, so it is now "I2CHelper".
Repo is here: https://github.com/Basirk/I2CHelper
The current release is 1.0.4, which has an updated library.properties file.

Many thanks!

**Comment by per1234** [comment]
Hi @Basirk. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue or the associated pull request (https://github.com/arduino/library-registry/pull/347), you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by rsora** [comment]
Solved by #347
