### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/library-registry#3474]
### Library repository URL

https://github.com/Silver-Fang/ArduinoSTL

**Comment by per1234** [comment]
Hi @Silver-Fang. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/10/25 15:49:00 Loaded 6306 libraries from DB
Removing STL for Arduino
Success!
```
