### ISSUE TITLE
[Library Manager] Please add new library: Creative Robotix

### ISSUE THREAD

**Issue by segertonGH** [arduino/library-registry#3479]
Hello, 

Please could you add this new library to the library manager [https://github.com/segertonGH/Creative-Robotix-Educational-Platform-Arduino](https://github.com/segertonGH/Creative-Robotix-Educational-Platform-Arduino).

Thank you.

**Comment by per1234** [comment]
Hi @segertonGH. I saw you closed your issue already, but just in case you are interested, I'll mention that we have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
