### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by PTSolns** [arduino/library-registry#3493]
### Library repository URL

https://github.com/PTSolns/PTSolns_I2CBackpack

**Comment by PTSolns** [comment]
We submitted a new library last night but had a minor mistake in library name. Please help us update the library name. We accidently had a space in the name. Old name = "PTSolns I2CBackpack", New name = "PTSolns_I2CBackpack". Regards, MP

**Comment by per1234** [comment]
Hi @PTSolns. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/10/25 15:52:16 Loaded 6305 libraries from DB
Removing PTSolns I2CBackpack
Success!
```
