### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by beratcomputer** [arduino/library-registry#3621]
### Library repository URL

https://github.com/Acrome-Smart-Motor-Driver/SMD-Arduino-Library

**Comment by per1234** [comment]
Hi @beratcomputer. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
Hi @beratcomputer. I don't have any specific timeline for when the index maintainer will be able to accommodate your request. It might take a couple of weeks. Please be patient.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/11/22 16:43:40 Loaded 6390 libraries from DB
Removing Acrome SMD - Arduino Library
Success!
```
