### ISSUE TITLE
[Library Manager] Please add SchooMyUtilities

### ISSUE THREAD

**Issue by ryoimayoshi-schoomy** [arduino/library-registry#363]
Hello.

I created a library to manage my board named SchooMyBoard (that assembled with ATmega328).
Could you add this to a list of libraries?

url: https://github.com/SchooMyDevelopment/SchooMyUtilities

Thanks.

**Comment by per1234** [comment]
Hi @ryoimayoshi-schoomy. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
