### ISSUE TITLE
[Question]: removing a specific relese of a library

### ISSUE THREAD

**Issue by hasenradball** [arduino/library-registry#3632]
### Describe the request

Hi guys,

I had a Question regarding the Library indexer.
How can I achieve that a specific version will be removed from the index.

For example I provided a release 0.1.0 and a more improved one with 1.0.0.
And I want to remove the 0.1.0 from the index.

How  can I achieve this?

### Describe the current behavior

Is it possible to do this automatically by the Arduinobot?

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @hasenradball.

> I want to remove the 0.1.0 from the index.
>
>How can I achieve this?

The procedure for requesting the removal of a release is documented here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-remove-a-release-of-my-library-from-library-manager

If you have any questions or problems while following those instructions, feel free to comment here on this issue thread. I'll be happy to provide assistance.

>Is it possible to do this automatically by the Arduinobot?

No. We have only automated library submissions. All other types of operations are handled manually by the maintainers of this repository and the Library Manager index system. That means that it takes some time before we can get to accommodating release removal requests. But we are sure to get it done without too much delay.

**Comment by per1234** [comment]
>For example I provided a release 0.1.0 and a more improved one with 1.0.0.
And I want to remove the 0.1.0 from the index.

I should add that you shouldn't request the removal of releases frivolously. It should only be done in the case of a serious emergency such as if it was later discovered to contain copyrighted content used without permission of the owner.

In your example where you simply made an improvement to the library in the new release, you should NOT submit a removal request for the previous version. The process of removing a release is fairly time consuming so if library maintainers abuse the system to submit requests for such frivolous reasons we would be quickly overwhelmed by thousand of request and would have to stop offering this service.

The Arduino Library Manager always offers the newest version by default so a user would have to intentionally chose to install an older version. They will only ever install the older version of the library if there is a very good reason for doing so, such as if there is a serious regression or incompatibility in the latest version. Arduino Library Manager also automatically offers updates to those users using older versions of a library.
