### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by hasenradball** [arduino/library-registry#3633]
### Library name

https://github.com/hasenradball/AM2302-Sensor

### Version to remove

v0.1.0

**Comment by per1234** [comment]
The reason for requesting the removal of the release was provided in your other issue as:

> I provided a release 0.1.0 and a more improved one with 1.0.0.
> And I want to remove the 0.1.0 from the index.

This is not a valid reason for removal of a release so I will reject this. Removal requests should only be done in the case of a serious emergency such as if it was later discovered to contain copyrighted content used without permission of the owner.
