### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by Jueff** [arduino/library-registry#3769]
### Library name

MobaLedLib

### Version to remove

3.3.0

**Comment by Jueff** [comment]
Hi @per1234: Thank you for your fast feedback. I know that removing a release is a lot of manual work, I appreciate the work of the entire team, you are doing a great job.
I requested the removal because this release contains a major bug, that should NEVER come into field.It would allow installation of a library on ESP32 platform, where we don't have a license for.

**Comment by per1234** [comment]
OK, I am confirming your request @Jueff.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by usblink** [comment]
updated

**Comment by MatteoPologruto** [comment]
Done:
```
2023/12/27 16:01:16 Loaded 6484 libraries from DB
Removing MobaLedLib@3.3.0
Success!
```
