### ISSUE TITLE
EdgieD library has been updated but update has not progressed through to Arduino library manager.

### ISSUE THREAD

**Issue by crunchysteve** [arduino/library-registry#3890]
### Describe the problem

EdgieD library has been updated but update has not progressed through to Arduino library manager. Still showing as v 0.0.1, should be version 1.0.0

Thanks
Crunchysteve

### To reproduce

I forked, updated the library entry and pull-requested a few days ago

### Expected behavior

Expected the new library to appear in the app's library manager

### Additional context

Library EdgieD should have updated to new version by now

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @crunchysteve 

## Problem

It looks like you messed up when you created the `ArduinoLibrary` tag. You tagged the library at this commit from 2022:

https://github.com/crunchysteve/EdgieD/commit/cf1ee9601568f74a14971a43912fd7c7faf7f4cf

At that point in the library's development history, the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was set to 0.0.1.

You can see it here:

https://github.com/crunchysteve/EdgieD/blob/ArduinoLibrary/library.properties#L2

```text
version=0.0.1
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository. I recommend using the version number in the tag name. The library manager system doesn't care what the tag name is, but using a meaningless tag name like `ArduinoLibrary` is hostile to humans using your repository. You should also create a separate tag for each release and not delete or move the tag after you create it.

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by crunchysteve** [comment]
Thanks Per.

A relative newbie to this stuff, me, as you may have gathered.

Cheers,
Crunchy
