### ISSUE TITLE
Library name change request from "GPIObj" to "gpiobj"

### ISSUE THREAD

**Issue by simonlmn** [arduino/library-registry#3928]
### Library repository URL

https://github.com/simonlmn/gpiobj

**Comment by per1234** [comment]
Hi @simonlmn. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/01/25 17:02:28 Loaded 6588 libraries from DB
Removing GPIObj
Success!
```
