### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by yhur** [arduino/library-registry#4001]
### Library name

ConfigPortal8266

### Version to remove

0.1.0

**Comment by per1234** [comment]
Hi @yhur. There never was a 1.0 release of the library:

![image](https://github.com/arduino/library-registry/assets/8572152/b6d61c6a-059e-4e11-939f-78cc326bced1)

Did you intend to request the removal of the 0.1.0 release?

**Comment by yhur** [comment]
Yes, you're right. That's what I wanted to remove.
Sorry for the confusion and I appreciate your insight here.

**Comment by per1234** [comment]
Thanks for the clarification. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

**Comment by yhur** [comment]
Great! Thanks

**Comment by MatteoPologruto** [comment]
Done:
```
2024/02/08 16:46:31 Loaded 6631 libraries from DB
Removing ConfigPortal8266@0.1.0
Success!
```
