### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by holgerlembke** [arduino/library-registry#4026]
### Library repository URL

https://github.com/holgerlembke/st7567sfGK

**Comment by holgerlembke** [comment]
I'm so sorry.

I wished it was clearer to me, that the name is the main indexing item and therefor can not be changed that easily.

**Comment by per1234** [comment]
Hi @holgerlembke. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by holgerlembke** [comment]
❤️

**Comment by MatteoPologruto** [comment]
Done:
```
2024/02/15 13:41:01 Loaded 6650 libraries from DB
Removing st7567sfGK
Success!
```

**Comment by holgerlembke** [comment]
❤️
