### ISSUE TITLE
Library name change request EByte_LoRa_E70_Series_Library to EByte_RF_E70_Series_Library

### ISSUE THREAD

**Issue by xreef** [arduino/library-registry#4033]
### Library repository URL

https://github.com/xreef/EByte_LoRa_E70_Series_Library

**Comment by xreef** [comment]
Hi,
sorry for the inconvenience, but in the original repository, I wrote a word that isn't true. The device works as a LoRa device but does not use LoRa modulation and is proprietary of Semtech, so I must change the name like in the description and the repository name also.
If you prefer you can delete the library, and I will redò the subscription.
Sorry Renzo

**Comment by per1234** [comment]
Hello @xreef. I see you have already updated the value in the `name` metadata field. However, Library Manager works exclusively from Git tags, so the system won't be able to see the change until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that version still has the old name:

https://github.com/xreef/EByte_RF_E70_Series_Library/blob/v0.0.10/library.properties#L1

```text
name=EByte LoRa E70 library
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, add a comment here to let us know we can proceed with the renaming operation.

If you have any questions or concerns, please let me know.

Regards, Per

>If you prefer you can delete the library, and I will redò the subscription.

No, this is the correct procedure to follow.

> and the repository name also.

OK, we will take care of that at the same time as updating the registered name.

**Comment by xreef** [comment]
I create the release.
Thanks RM

**Comment by per1234** [comment]
OK, great. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/02/15 13:51:22 Loaded 6647 libraries from DB
Removing EByte LoRa E70 library
Success!
```
