### ISSUE TITLE
Official wolfSSL library and old 3rd party both in library index.

### ISSUE THREAD

**Issue by gojimmypi** [arduino/library-registry#4101]
### Describe the problem

Hi @per1234 

I see the new [Official wolfSSL](https://github.com/wolfSSL/Arduino-wolfSSL.git) is in the [The Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) but the old, 3rd party version from `onelife` is still there, too. 

Those versions (`5.5.4` and `4.7.1`) are not Official wolfSSL repositories and do not even work as noted in https://github.com/wolfSSL/wolfssl/issues/6360 and the [wolfssl forum](https://www.wolfssl.com/forums/post7405.html#p7405).

My Arduino IDE only sees the old one, not the new official one. Any suggestions?

```
    {
      "name": "wolfssl",
      "version": "4.7.1",
      "author": "www.wolfssl.com",
      "maintainer": "onelife \u003conelife.real@gmail.com\u003e",
      "sentence": "wolfSSL Embedded SSL/TLS Library for Arduino",
      "paragraph": "The wolfSSL embedded SSL library is a lightweight SSL/TLS library written in ANSI C and targeted for embedded, RTOS, and resource-constrained environments - primarily because of its small size, speed, and feature set.",
      "website": "https://github.com/onelife/Arduino_wolfssl",
      "category": "Communication",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ],
      "repository": "https://github.com/wolfSSL/Arduino-wolfSSL.git",
      "providesIncludes": [
        "wolfssl.h"
      ],
      "url": "https://downloads.arduino.cc/libraries/github.com/wolfSSL/wolfssl-4.7.1.zip",
      "archiveFileName": "wolfssl-4.7.1.zip",
      "size": 5535395,
      "checksum": "SHA-256:b332f51ee3015903a46feffa6738128bf045f17e8b0cdab410ff625f1373a0c0"
    },
    {
      "name": "wolfssl",
      "version": "5.5.4",
      "author": "www.wolfssl.com",
      "maintainer": "onelife \u003conelife.real@gmail.com\u003e",
      "sentence": "wolfSSL Embedded SSL/TLS Library for Arduino",
      "paragraph": "The wolfSSL embedded SSL library is a lightweight SSL/TLS library written in ANSI C and targeted for embedded, RTOS, and resource-constrained environments - primarily because of its small size, speed, and feature set.",
      "website": "https://github.com/onelife/Arduino_wolfssl",
      "category": "Communication",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ],
      "repository": "https://github.com/wolfSSL/Arduino-wolfSSL.git",
      "providesIncludes": [
        "wolfssl.h"
      ],
      "url": "https://downloads.arduino.cc/libraries/github.com/wolfSSL/wolfssl-5.5.4.zip",
      "archiveFileName": "wolfssl-5.5.4.zip",
      "size": 11371241,
      "checksum": "SHA-256:7028e4c78fed163c1daa38517c1ad452e84e5adb60fc6bc8a50863e1bbc07f31"
    },
    {
      "name": "wolfssl",
      "version": "5.6.6-Arduino.1",
      "author": "wolfSSL inc",
      "maintainer": "wolfSSL inc \u003csupport@wolfssl.com\u003e",
      "sentence": "A lightweight SSL/TLS library written in ANSI C and targeted for embedded, RTOS, and resource-constrained environments.",
      "paragraph": "Manual: https://www.wolfssl.com/documentation/manuals/wolfssl/index.html.",
      "website": "https://www.wolfssl.com/",
      "category": "Communication",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ],
      "repository": "https://github.com/wolfSSL/Arduino-wolfSSL.git",
      "url": "https://downloads.arduino.cc/libraries/github.com/wolfSSL/wolfssl-5.6.6-Arduino.1.zip",
      "archiveFileName": "wolfssl-5.6.6-Arduino.1.zip",
      "size": 9937716,
      "checksum": "SHA-256:939799246e1db69f0c865507c7602858b86350ad56cb40db0c3caca5d1858931"
    },
```

### To reproduce

See [The Library Manager index](http://downloads.arduino.cc/libraries/library_index.json)

### Expected behavior

Only the Official wolfSSL library should be present.

### Additional context

See also See https://github.com/arduino/library-registry/pull/4056

Update: I do see the new wolfSSL in the Arduino app, along with the old versions that should please be removed.

I could probably arrange to create Official wolfSSL releases for those exact versions, if desired?

![image](https://github.com/arduino/library-registry/assets/13059545/acdc4182-b1f6-437c-82e6-99f3a5491abc)

References to wolfSSL should only contain the Official wolfSSL:

```
    {
      "name": "wolfssl",
      "version": "5.6.6-Arduino.1",
      "author": "wolfSSL inc",
      "maintainer": "wolfSSL inc \u003csupport@wolfssl.com\u003e",
      "sentence": "A lightweight SSL/TLS library written in ANSI C and targeted for embedded, RTOS, and resource-constrained environments.",
      "paragraph": "Manual: https://www.wolfssl.com/documentation/manuals/wolfssl/index.html.",
      "website": "https://www.wolfssl.com/",
      "category": "Communication",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ],
      "repository": "https://github.com/wolfSSL/Arduino-wolfSSL.git",
      "url": "https://downloads.arduino.cc/libraries/github.com/wolfSSL/wolfssl-5.6.6-Arduino.1.zip",
      "archiveFileName": "wolfssl-5.6.6-Arduino.1.zip",
      "size": 9937716,
      "checksum": "SHA-256:939799246e1db69f0c865507c7602858b86350ad56cb40db0c3caca5d1858931"
    },
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @gojimmypi. Since https://github.com/arduino/library-registry/pull/4056 was only a request to change the registered repository URL for an existing library, the entries for the previous releases of the library were not removed from the Library Manager index.

If you would like to request the removal of releases, please follow this procedure:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-remove-a-release-of-my-library-from-library-manager

**Comment by gojimmypi** [comment]
Hi @per1234 

I've used the template and created https://github.com/arduino/library-registry/issues/4135 and https://github.com/arduino/library-registry/issues/4136

**Comment by gojimmypi** [comment]
Hi @per1234 - just wanted to say thanks for all the help! I have the Official wolfSSL all setup now. 

https://github.com/wolfSSL/Arduino-wolfSSL

Status:

https://downloads.arduino.cc/libraries/logs/github.com/wolfSSL/Arduino-wolfSSL/
