### ISSUE TITLE
LcdMenu Library version not up to date

### ISSUE THREAD

**Issue by forntoh** [arduino/library-registry#4120]
### Describe the problem

The latest version in the library manager is 3.5.0, whereas I have submitted 3 other releases. Why doesn't it update?

### To reproduce

Just go to the library manager and search for LcdMenu, the version shown is 3.5.0

### Expected behavior

The version should be 3.5.3 as of the time of creation of this issue

### Additional context

https://github.com/forntoh/LcdMenu
It is my library.

Logs
https://downloads.arduino.cc/libraries/logs/github.com/forntoh/LcdMenu/

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @forntoh. The newer releases are there in my Arduino IDE Library Manager as expected:

![image](https://github.com/arduino/library-registry/assets/8572152/b8974dd1-b33e-4b99-9e4f-5e0d002268b7)

I also checked in Arduino IDE 1.8.19 and I see them there as well.

Which version of Arduino IDE are you using?

Does your IDE have access to the Internet?

**Comment by forntoh** [comment]
I am using the one that comes built in with the Arduino plugin for VS Code. If you go to the repository, you will also notice that the first badge in the readme stopped updating after v3.5.0

**Comment by per1234** [comment]
OK, thanks for the clarification. Arduino does not maintain or support the VS Code extension or ardu-badge.com so reports of problems you encounter when using them are off topic for this issue tracker.

You are welcome to request support for using these 3rd party products on the Arduino Forum:

https://forum.arduino.cc/
