### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by gojimmypi** [arduino/library-registry#4135]
### Library name

wolfssl

### Version to remove

5.5.4

**Comment by gojimmypi** [comment]
See https://github.com/arduino/library-registry/pull/4056 and https://github.com/arduino/library-registry/issues/4101

**Comment by per1234** [comment]
Hi @gojimmypi. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/02/29 14:55:35 Loaded 6704 libraries from DB
Removing wolfssl@5.5.4
Success!
```

**Comment by gojimmypi** [comment]
Confirmed. Thank you!
