### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by gojimmypi** [arduino/library-registry#4136]
### Library name

wolfssl

### Version to remove

4.7.1

**Comment by gojimmypi** [comment]
See https://github.com/arduino/library-registry/pull/4056 and https://github.com/arduino/library-registry/issues/4101

**Comment by MatteoPologruto** [comment]
Done:
```
2024/02/29 14:56:29 Loaded 6704 libraries from DB
Removing wolfssl@4.7.1
Success!
```

**Comment by gojimmypi** [comment]
Confirmed. Thank you!
