### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by ricardoquesada** [arduino/library-registry#4167]
### Library repository URL

https://github.com/ricardoquesada/bluepad32-arduino

**Comment by ricardoquesada** [comment]
I'd like to rename it from "Bluepad32" to "Bluepad32 for NINA-W10 boards".

Rationale: Bluepad32 is generic library that already supports multiple boards. But this specific library only supports the Arduino boards that are using NINA-W10x boards as co-processors.

Thanks!

**Comment by per1234** [comment]
Hi @ricardoquesada. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/03/07 16:45:39 Loaded 6728 libraries from DB
Removing Bluepad32
Success!
```
