### ISSUE TITLE
[Library Manager] Please add JoystickESP32.

### ISSUE THREAD

**Issue by Yigit-Abacioglu** [arduino/library-registry#4182]
Could you please add the JoystickESP32 library to the Library Manager?

[https://github.com/Yigit-Abacioglu/JoysticESP32](url)

It's a simple Joystick library

**Comment by per1234** [comment]
Hi @Yigit-Abacioglu. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
