### ISSUE TITLE
Delete Library from Library Manager

### ISSUE THREAD

**Issue by treeaa** [arduino/library-registry#428]
Please help remove this library：https://github.com/treeaa/BME33M251

**Comment by per1234** [comment]
Hello @treeaa. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked issue/PR, you'll get a notification at that time.

**Comment by per1234** [comment]
Putting on hold until @treeaa provides an explanation for https://github.com/arduino/library-registry/pull/438

**Comment by treeaa** [comment]
Dear sir,
    I requested the library be removed yesterday,but I can still find it from Arduino IDE.I mistakenly thought it could not be deleted, so I added it again.
    Now,I already know it can be deleted. Please help delete this library.Sorry for the inconvenience.
     Thanks.

**Comment by rsora** [comment]
Solved by #430
