### ISSUE TITLE
Adding a library

### ISSUE THREAD

**Issue by addowneer01** [arduino/library-registry#4312]
### Describe the problem

The bot reports that the file is missing, although it is there.
I tried to correct the name several times and was case-sensitive.
https://github.com/addowneer01/CraftConnect-library-for-Arduino-ESP8266/tree/main
![Скриншот 06-04-2024 135835](https://github.com/arduino/library-registry/assets/92033724/a85339a3-5f4e-4a42-a8ba-b5ad95a2774d)

### To reproduce

.

### Expected behavior

.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @addowneer01. I have provided an explanation of the problem and what you need to do to resolve it here:

https://github.com/arduino/library-registry/pull/4311#pullrequestreview-1984573719
