### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by Gitshaoxiang** [arduino/library-registry#4326]
### Library repository URL

https://github.com/m5stack/M5PoECAM

**Comment by Gitshaoxiang** [comment]
the PR: https://github.com/arduino/library-registry/pull/4325

**Comment by per1234** [comment]
Hi @Gitshaoxiang. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/04/11 14:47:00 Loaded 6824 libraries from DB
Removing PoE_CAM
Success!
```
