### ISSUE TITLE
Library release 1.2.1 removal request for M5StackMenuSystem

### ISSUE THREAD

**Issue by chhorisberger** [arduino/library-registry#4367]
### Library name

M5StackMenuSystem

### Version to remove

1.2.1

**Comment by chhorisberger** [comment]
I accidentally created a 1.2.1 version for my library, even tough 1.1.3 should have been the next logical release number.
Could you please remove the version 1.2.1 from the registry?
Thank you very much and have a nice day!

**Comment by per1234** [comment]
Hi @chhorisberger. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/04/18 14:50:14 Loaded 6842 libraries from DB
Removing M5StackMenuSystem@1.2.1
Success!
```

**Comment by chhorisberger** [comment]
Thank you very much
