### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by CodeAsm** [arduino/library-registry#4385]
### Library name

https://github.com/Khuuxuanngoc/DHT-sensor-library

### Version to remove

v3.4.4

**Comment by CodeAsm** [comment]
It does NOT add anything of value besides the original library. 
https://github.com/adafruit/DHT-sensor-library/compare/master...Khuuxuanngoc:DHT-sensor-library:master
changes

**Comment by per1234** [comment]
Hi @CodeAsm. Thanks for your interest in the curation of the Arduino Library Manager. We only accept removal requests that have been approved by the library maintainer. So I must decline your request.

I would suggest for you to present your concerns directly to @Khuuxuanngoc. If you obtain their approval then you are welcome to submit another removal request with a link to the statement of approval.

Regards,
Per

**Comment by CodeAsm** [comment]
Ive send an email to them 
Their email adress wasnt set in the library.properties correctly 

(ow apparently they do know howto: https://github.com/Khuuxuanngoc/Hshopvn_GSM/blob/master/library.properties)
