### ISSUE TITLE
Rename M5_Finger to M5_FPC1020A

### ISSUE THREAD

**Issue by Tinyu-Zhao** [arduino/library-registry#442]
I tried to change the name of the library to make it more precise
#441

**Comment by Tinyu-Zhao** [comment]
Thank you for your help

**Comment by per1234** [comment]
Hello @Tinyu-Zhao. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked PR, you'll get a notification at that time: https://github.com/arduino/library-registry/pull/443

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager
