### ISSUE TITLE
GSM (inside the mbed core) and GSM (standalone) have same library name

### ISSUE THREAD

**Issue by aliphys** [arduino/library-registry#4555]
### Describe the problem

User can access two libraries named `GSM` that are accessible from the IDE.
- [arduino/ArduinoCore-mbed/tree/main/libraries/GSM](https://github.com/arduino/ArduinoCore-mbed/tree/main/libraries/GSM) (inside the mbed core)
- [arduino-libraries/GSM](https://github.com/arduino-libraries/GSM) (standalone)

This raises several concerns:
- The name of both libraries (inside the [core](https://github.com/arduino/ArduinoCore-mbed/blob/dd5abb6171063b2777620b9339510c63b915ce72/libraries/GSM/library.properties#L1) as well as the [standalone](https://github.com/arduino-libraries/GSM/blob/b8a6f9d0fcd09ab0283ec72e765dea4f8887f834/library.properties#L1)) is the same, according to the first line of their respective `library.properties` files. -> `name=GSM`
- The external library is retired, yet there is no indication this is so in any of the [fields](https://github.com/arduino-libraries/GSM/blob/b8a6f9d0fcd09ab0283ec72e765dea4f8887f834/library.properties#L1-L9). The GSM standalone library has been archived, with the last release in August 2018 (over 5 years ago) yet is shows up as the **first** result when searching for GSM in the library manager 

- The internal GSM library in the mbed core, has no description apart from `sentence=GSM wrapper`. 
- If a non-mbed board is selected and both libraries are loaded, then `#include "GSM.h"` will select the standalone library. However, the standalone library only supports the [avr](https://github.com/arduino-libraries/GSM/blob/b8a6f9d0fcd09ab0283ec72e765dea4f8887f834/library.properties#L9) platform. This would create a black hole in `arduino:renesas_portenta` and `arduino:samd` users seeking to use GSM functionality. 

### To reproduce

1. Open the Arduino IDE
2. With a mbed board selected, click on File -> Examples. Noticed the GSM library included there
![image](https://github.com/arduino/library-registry/assets/75624145/70a6725a-3b25-42a0-8e1c-e25b5596a3a5)
3. Go to the Library manager in the IDE. Search for `GSM`. This is the retired GSM library yet this is not mentioned
![Untitled](https://github.com/arduino/library-registry/assets/75624145/6c77e55a-06eb-463a-8742-99c02978e158)

### Expected behavior

- The external library is marked as [RETIRED] or similar
- There is a clear description of the scope (`sentence` and `paragraph` fields filled in) for the internal [arduino/ArduinoCore-mbed/tree/main/libraries/GSM](https://github.com/arduino/ArduinoCore-mbed/tree/main/libraries/GSM) library
- A alternative library is provided instead of the standalone GSM library for non `mbed` boards

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @aliphys. 

> The external library is retired, yet there is no indication

This will be resolved by https://github.com/arduino/library-registry/pull/4556

> The internal GSM library in the mbed core, has no description apart from `sentence=GSM` wrapper.

That is off topic for this repository. You can submit a pull request to the repository where that library is hosted:

https://github.com/arduino/ArduinoCore-mbed

> If a non-mbed board is selected and both libraries are loaded, then #include "GSM.h" will select the standalone library.

This is off topic for this repository, it is also exactly how the Arduino sketch build system is designed to work. ["Platform bundled" library](https://arduino.github.io/arduino-cli/latest/platform-specification/#platform-bundled-libraries) are only discoverable by the sketch build system when a board of that platform is selected.

> A alternative library is provided instead of the standalone GSM library for non mbed boards

Of course registration of such a library will be welcome, but the subject of creation of the library is off topic here.

**Comment by aliphys** [comment]
>That is off topic for this repository. You can submit a pull request to the repository where that library is hosted:
https://github.com/arduino/ArduinoCore-mbed

Thanks! Documented issue here -> https://github.com/arduino/ArduinoCore-mbed/issues/886

**Comment by MatteoPologruto** [comment]
Done:
```
2024/05/23 14:47:52 Loaded 6939 libraries from DB
Success!
```
