### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by psachs** [arduino/library-registry#4576]
### Library repository URL

https://github.com/Sensirion/arduino-uart-sfx6xxx

**Comment by per1234** [comment]
Hi @psachs. I see the name of the library has been changed in the library metadata:

https://github.com/Sensirion/arduino-uart-sfx6xxx/commit/6de27e1c844eada0078b66a5b564f03437f84d58

However, Library Manager works exclusively from Git tags, so the system wouldn't be able to process the name change until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the Library Manager system would see now still has the currently registered name:

https://github.com/Sensirion/arduino-uart-sfx6xxx/blob/1.0.0/library.properties#L1

```text
name=SensirionUartSfx6xxx
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, please add a comment here on the issue thread to let us know we can proceed with the name change request.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by psachs** [comment]
I updated the version in library.properties and created a 1.1.0 tag. The repository should therefore be ready for renaming.

Regards, Pascal

**Comment by per1234** [comment]
Hi @psachs. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/06/13 14:55:21 Loaded 7066 libraries from DB
Removing SensirionUartSfx6xxx
Success!
```
