### ISSUE TITLE
X-NUCLEO-NFC05A1 libraries still not available on the library manager

### ISSUE THREAD

**Issue by cparata** [arduino/library-registry#459]
Hi all,
I successfully submitted 3 libraries to support the X-NUCLEO-NFC05A1 expansion board. You can find the commit [here](https://github.com/arduino/library-registry/commit/075478287ffdb288c2a4a7ec396d50aff2f184d2). But the libraries are still not available on the Arduino Library Manager even if the commit was integrated last Friday. What could be the issue?
Best Regards,
Carlo

**Comment by cmaglie** [comment]
I can see them now:

```
Name: "STM32duino X-NUCLEO-NFC05A1"
  Author: STMicroelectronics
  Maintainer: stm32duino
  Sentence: Allows controlling the ST X-NUCLEO-NFC05A1 expansion board
  Paragraph: This library provides a sample application to control ST X-NUCLEO-NFC05A1 expansion board
  Website: https://github.com/stm32duino/X-NUCLEO-NFC05A1
  Category: Communication
  Architecture: stm32
  Types: Contributed
  Versions: [1.0.0]
  Dependencies: STM32duino NFC-RFAL, STM32duino ST25R3911B

Name: "STM32duino NFC-RFAL"
  Author: STMicroelectronics
  Maintainer: stm32duino
  Sentence: Allows controlling the ST NFC card reader components based on RFAL
  Paragraph: This library provides the implementation of the RF/NFC abstraction layer (RFAL)
  Website: https://github.com/stm32duino/NFC-RFAL
  Category: Communication
  Architecture: stm32
  Types: Contributed
  Versions: [1.0.0]

Name: "STM32duino ST25R3911B"
  Author: STMicroelectronics
  Maintainer: stm32duino
  Sentence: Allows controlling the ST ST25R3911B component
  Paragraph: This library provides an implementation of the NFC RFAL for ST25R3911B component
  Website: https://github.com/stm32duino/ST25R3911B
  Category: Communication
  Architecture: stm32
  Types: Contributed
  Versions: [1.0.0]
  Dependencies: STM32duino NFC-RFAL
```

It takes some time for the CDN cache to update, it could be that you checked too early?

**Comment by per1234** [comment]
Thanks so much for bringing this issue to our attention @cparata. It has now been resolved and you can see from the logs pages of your libraries that they have been indexed:
- http://downloads.arduino.cc/libraries/logs/github.com/stm32duino/NFC-RFAL/
- http://downloads.arduino.cc/libraries/logs/github.com/stm32duino/ST25R3911B/
- http://downloads.arduino.cc/libraries/logs/github.com/stm32duino/X-NUCLEO-NFC05A1/

As **cmaglie** mentioned, there is some caching of the index, both locally and in the CDN, so it might still be some time (we give a conservative estimate of "within a day's time") before the libraries become available for installation via Library Manager to everyone everywhere, but they are surely on their way.

**Comment by cparata** [comment]
Ok, thanks for the support
