### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by felixthecat8a** [arduino/library-registry#4591]
### Library repository URL

https://github.com/felixthecat8a/LCD_BacklightRGB

**Comment by felixthecat8a** [comment]
The url in the library manager list is correct, but the `name` property in the library.properties was incorrect.

**Comment by per1234** [comment]
Hi @felixthecat8a. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/06/13 14:56:52 Loaded 7065 libraries from DB
Removing LCD_BackgroundRGB
Success!
```
