### ISSUE TITLE
Remove release: `EscapeAutomate@0.0.1`

### ISSUE THREAD

**Issue by LioRei** [arduino/library-registry#467]
Hi,

could you update my lib =>https://github.com/EscapeAutomate/ArduinoLib

I've deleted the tag 0.0.1 because it contain sensible information.

Thanks !

**Comment by rsora** [comment]
Worker maintenance done:

```
2021/09/23 18:06:47 Loaded 4222 libraries from DB
Removing EscapeAutomate@0.0.1
Success!
```
