### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by maarten-pennings** [arduino/library-registry#4815]
### Library repository URL

https://github.com/ams-OSRAM-Group/OSP_aoresult

**Comment by maarten-pennings** [comment]
If it is easier, faster, or safer, I can also delete the repo, and create it again, with only the second release, skipping the first release with the wrong name.

**Comment by per1234** [comment]
> I can also delete the repo, and create it again

@maarten-pennings please don't do that. You are following the proper procedure. Anything else will only cause confusion and wasted time. We will get to your request as soon as we are able. Please be patient.

**Comment by maarten-pennings** [comment]
Thanks for answering.
I just wanted to check if I could do work on my side instead of having you do work.
I was right to ask you first - not wise to delete my repo.
I will be patient :-)

Having said that, I do want to release a library (aoosp) that depends on this one (aoresult), and the dependency clause (in aoosp) uses the new name of aoresult. But since aoresult (with new name) is not yet available I don't dare to release aoosp. So I'm a bit motivated to move one.

**Comment by per1234** [comment]
Hi @maarten-pennings. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done in https://github.com/arduino/library-registry/pull/4855#pullrequestreview-2205002023
