### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by davidlmorris** [arduino/library-registry#4837]
### Library repository URL

https://github.com/davidlmorris/debuggery

**Comment by davidlmorris** [comment]
The change was from Debuggery to debuggery.  Having a capital letter in the header file looks wrong.  

IMHO this ought to be a case-insensitive test.

**Comment by per1234** [comment]
Hi @davidlmorris. You had already changed the name in the library metadata at the time you submitted the library (https://github.com/arduino/library-registry/pull/4842) so it was registered with the intended name "debuggery":

![image](https://github.com/user-attachments/assets/8713af77-92af-405b-81d7-eff76e3dc0f2)

This means that no action is needed and so I'll close this issue.

**Comment by davidlmorris** [comment]
I noticed that yesterday too.  And, I had thought there had been a manual change.  I had run arduino-lint (and installed it as an action on Github), and it was failing every time with: 

```
Linting library in /home/runner/work/debuggery/debuggery
ERROR: Library name debuggery not found in the Library Manager index. Library names are not allowed to change after     
       being added to the index.                                                                                        
       See: https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name               
       (Rule LP018)   
```
This after several tag and version bumps, so I had assumed that there was some other index associated with arduino-lint.  I added the name to the index a few days ago, along with a version and tag bump, wondering if "Library name debuggery not found in the Library Manager index" was significant, however, that did not seem to make any difference (until apparently the other day).

Thank you for following up.
