### ISSUE TITLE
Indus-Board-TouchLED Library

### ISSUE THREAD

**Issue by Satywanti** [arduino/library-registry#4885]
[IndusBoardTouchLED.zip](https://github.com/user-attachments/files/16425083/IndusBoardTouchLED.zip)
Library to control LED using touch on Indus Board 
Creator - Ashwini Kumar Sinha, Satywanti, Abhay Verma, Manjeet Vishwakarma 
Link - https://indus.electronicsforu.com/ 
**Keywords to control LED:** 
int readCapacitance(); 
bool touch(); 
void controlLED();

**Comment by per1234** [comment]
Hi @Satywanti. I'm not sure I understand the purpose of your issue.

Are you only trying to share the news of the availability of your library with the Arduino community? If so, the GitHub issue tracker is not an appropriate place for this. The issue tracker should only be used to submit formal bug reports or feature requests. The appropriate place for other communications and discussions is Arduino Forum, where we even have a dedicated "Libraries" category:

https://forum.arduino.cc/c/development/libraries/39

---

Or perhaps you intended to submit your library for inclusion in the [Arduino Library Manager](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-installing-a-library#installing-a-library)? If so, we have a formal system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
