### ISSUE TITLE
Indus Board control

### ISSUE THREAD

**Issue by abhayverma21** [arduino/library-registry#4886]
[IndusBoard.zip](https://github.com/user-attachments/files/16425082/IndusBoard.zip)
Library to  control sensor and built-in LED of Indus Board 
Creator - Ashwini Kumar Sinha, Abhay Verma, Satywanti, Manjeet Vishwakarma
Link - https://indus.electronicsforu.com/
**Keywords to control Indus Board sensor and LED**:
// Control the built-in LED
    Board.led("on");
    delay(1000);
    Board.led("off");
    delay(1000);
    Board.led(128); // Set brightness to 50%
    delay(1000);
Board.readAll()

**Comment by per1234** [comment]
Hi @abhayverma21. I'm not sure I understand the purpose of your issue.

Are you only trying to share the news of the availability of your library with the Arduino community? If so, the GitHub issue tracker is **NOT** an appropriate place for this. The issue tracker should only be used to submit formal bug reports or feature requests. The appropriate place for other communications and discussions is Arduino Forum, where we even have a dedicated "Libraries" category:

https://forum.arduino.cc/c/development/libraries/39

---

Or perhaps you intended to submit your library for inclusion in the [Arduino Library Manager](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-installing-a-library#installing-a-library)? If so, we have a formal system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
