### ISSUE TITLE
Change library name to avdweb_Switch

### ISSUE THREAD

**Issue by nomakewan** [arduino/library-registry#4991]
### Library repository URL

https://github.com/avandalen/avdweb_Switch

**Comment by per1234** [comment]
Hi @nomakewan. I must verify that the requested name change is approved by one of the official maintainers of the library before proceeding. Please either provide a link to an existing public statement of approval, or else request the maintainer provide one (they can do it as a comment here, in an issue in the library repository, etc.)

It looks like the active maintainer is @boseji. @boseji would you like us to change the registered library name from `Switch` to `avdweb_Switch`, as is now defined in the library metadata?

https://github.com/avandalen/avdweb_Switch/blob/1.2.5/library.properties#L1

Information about library name changes:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

Note that changing a library's name is potentially disruptive:

- The releases of the library under the old name will no longer be available for installation via the Arduino Library Manager
- It will be a breaking change for any dependent projects that specify the dependency (either [in their metadata](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format:~:text=on%20the%20list.-,depends,-%2D%20(available%20from), [project management file](https://arduino.github.io/arduino-cli/dev/sketch-project-file/#build-profiles), or documentation) using the previous name.

**Comment by boseji** [comment]
I have tried to fix this in the latest release. Please verify.
It was basically a copy paste mistake in updating the Properties file.

**Comment by nomakewan** [comment]
Closing request as the maintainer has reverted the name change.

**Comment by per1234** [comment]
> I have tried to fix this in the latest release. Please verify.

I verify. The 1.2.6 release, which has the registered name in the `name` field of its metadata has been successfully indexed by Library Manager:

![image](https://github.com/user-attachments/assets/c26d2e75-b87c-4a40-b921-60b4c2a702a5)

Thanks @nomakewan for your care for the Library Manager and thanks @boseji for your assistance with the handling of this request!
