### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by maciekish** [arduino/library-registry#5026]
Hi, i updated the library.preferences yesterday **before** submitting to repositories.txt but the library has now appeared in Arduino IDE with the old metadata. Where is this pulled from? The latest library.properties in git or from the latest zipped release? Can you please refresh the metadata? The name is slightly different and there is a 0.3.10 version that doesnt appear in Arduino IDE. Please use the name from library.preferences (DCS-BIOS) so that it is the same both in Arduino IDE and PlatformIO. Thank you.

### Library repository URL

https://github.com/DCS-Skunkworks/dcs-bios-arduino-library

**Comment by per1234** [comment]
Hi @maciekish.

> Where is this pulled from? The latest library.properties in git or from the latest zipped release?

Neither. Arduino Library Manager works from Git tags. The library is registered under the name from the `name` field of the `library.properties` metadata at the latest tag. At the time of registration, that was `DCS-BIOS FP-Fork`:

https://github.com/DCS-Skunkworks/dcs-bios-arduino-library/blob/0.3.9/library.properties#L1

```text
name=DCS-BIOS FP-Fork
```

As for the manually created ZIP file you add to the GitHub release assets, the Arduino Library Manager indexer doesn't know or care anything about it. The library archives that are distributed by Library Manager are made from the contents of the Git repository at each tag.

> Please use the name from library.preferences (DCS-BIOS) 

I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by maciekish** [comment]
Hi, thank you for the explanation. Do you know why it hasn't picked up 0.3.10 yet? Is it because the name has changed?

**Comment by per1234** [comment]
> Is it because the name has changed?

Yes. The library is locked to the name it was registered under. The indexer will reject any release that has a different `name` value in its metadata.

If you check [the indexer logs page](https://github.com/arduino/library-registry/pull/5021#issuecomment-2307411556) for your library, you can see the problem:

```text
2024/08/24 23:36:53 Checking out tag: 0.3.10
2024/08/24 23:36:53 Release DCS-BIOS:0.3.10 has wrong library name, should be DCS-BIOS FP-Fork
```

**Comment by maciekish** [comment]
> > Is it because the name has changed?
> 
> 
> 
> Yes. The library is locked to the name it was registered under. The indexer will reject any release that has a different `name` value in its metadata.
> 
> 
> 
> If you check [the indexer logs page](https://github.com/arduino/library-registry/pull/5021#issuecomment-2307411556) for your library, you can see the problem:
> 
> 
> 
> ```text
> 
> 2024/08/24 23:36:53 Checking out tag: 0.3.10
> 
> 2024/08/24 23:36:53 Release DCS-BIOS:0.3.10 has wrong library name, should be DCS-BIOS FP-Fork
> 
> ```
> 
> 

Thank you. We'll wait for the manual name change then. Sorry for the extra work.

**Comment by MatteoPologruto** [comment]
Done:
```
2024/09/12 15:49:38 Loaded 7300 libraries from DB
Removing DCS-BIOS FP-Fork
Success!
```
