### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by IRDMPE** [arduino/library-registry#5091]
### Library repository URL

https://gitlab.com/iridium/9704_launch_pad/arduino_library

**Comment by per1234** [comment]
Hi @IRDMPE. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/09/12 15:53:42 Loaded 7298 libraries from DB
Removing Iridium 9704 Launch Pad
Success!
```

**Comment by IRDMPE** [comment]
@MatteoPologruto Hey! Does this mean I can go through the normal registration procedure now?

**Comment by per1234** [comment]
@IRDMPE you don't need to do anything at all. The library name has been changed as you requested.

The reason you see "Removing Iridium 9704 Launch Pad" in the logs that were shared by Matteo is that the way we perform a name change is to remove the index entries under the old name, then reindex the library under the new name. You don't see anything about the reindexing in the logs because the reindexing happens automatically through a scheduled job that runs hourly.

**Comment by IRDMPE** [comment]
> @IRDMPE you don't need to do anything at all. The library name has been changed as you requested.
> 
> The reason you see "Removing Iridium 9704 Launch Pad" in the logs that were shared by Matteo is that the way we perform a name change is to remove the index entries under the old name, then reindex the library under the new name. You don't see anything about the reindexing in the logs because the reindexing happens automatically through a scheduled job that runs hourly.

I am a bit confused then, the indexer log doesn't seem to have updated 
https://[downloads.arduino.cc/libraries/logs/gitlab.com/iridium/9704_launch_pad/arduino_library/](https://downloads.arduino.cc/libraries/logs/gitlab.com/iridium/9704_launch_pad/arduino_library/)

It's hard to tell if the changes have occurred correctly. The version should be 0.8.15.

**Comment by IRDMPE** [comment]
Although, the actual IDE library manager tab appears correct.

**Comment by per1234** [comment]
Unfortunately the Arduino web team have instated a draconian caching policy on the indexer log web pages so they are often days out of date.

As you noticed, the actual Library Manager index has been updated even though the logs didn't reflect that. So all is well

**Comment by IRDMPE** [comment]
Awesome! Thank you all very much, and sorry for bungling this.
