### ISSUE TITLE
Request for adding library: libcli 1.0.4

### ISSUE THREAD

**Issue by tgtakaoka** [arduino/library-registry#511]
Please add `libcli 1.0.4` to library manager list.

name: command line support library
repository: https://github.com/tgtakaoka/libcli
tag: 1.0.4

Thanks.

**Comment by per1234** [comment]
Hi @tgtakaoka. Thanks for your interest in contributing to the Arduino Library Manager index! We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
