### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by mathieucarbou** [arduino/library-registry#5182]
### Library repository URL

https://github.com/mathieucarbou/ESPAsyncWebServer

**Comment by mathieucarbou** [comment]
`ESP Async WebServer` => `ESPAsyncWebServer`

To comply with Arduino library name conventions.

**Important notes:** 

- `https://github.com/mathieucarbou/ESPAsyncWebServer` fork is the community maintained fork of the original project at `https://github.com/me-no-dev/ESPAsyncWebServer` which is  left unmaintained

- @lacamera has uploaded a conflicted library (https://github.com/lacamera/ESPAsyncWebServer) which, IMO, should be removed (several Arduino users are complaining about it): see https://forum.arduino.cc/t/ide-library-manager-handling-of-duplicate-library-names/1306491 and https://github.com/arduino/library-registry/pull/4585 for the original removal request.

**Comment by per1234** [comment]
Hi @mathieucarbou. As you noted, the name "ESPAsyncWebServer" has already been claimed so we can not change your library's registered name to that.

You will need to select a unique name:

1. Change the `name` property in your library's `library.properties` metadata file to the unique name.
2. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
3. Comment here to let us know we can proceed with the renaming.

Or if you decide you prefer to stick with the current registered name "ESP Async WebServer", you can simply close this issue.

**Comment by mathieucarbou** [comment]
I think for now maybe the best option is for me to change it with:

```
name=ESP Async WebServer
includes=ESPAsyncWebServer.h
```
and issue a new release. 

Everywhere in the project `ESPAsyncWebServer` will be used, but `ESP Async WebServer` will only be used for the Arduino Registry name then.
