### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by McOrts** [arduino/library-registry#5214]
### Library repository URL

https://github.com/McOrts/WindQX_Library

**Comment by McOrts** [comment]
To fix the warning: https://github.com/arduino/library-registry/pull/5206#issuecomment-2396461803

**Comment by per1234** [comment]
Hi @McOrts. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/10/10 14:46:10 Loaded 7359 libraries from DB
Removing WindQX_Library
Success!
```
