### ISSUE TITLE
Library name change request: from 'TGX' to lowercase 'tgx'

### ISSUE THREAD

**Issue by vindar** [arduino/library-registry#5218]
### Library repository URL

https://github.com/vindar/tgx

**Comment by vindar** [comment]
For information:  I forget to create a new tag after changing the name of the library from `TGX` (upper case) to `tgx` (lowercase) and so I registered the library in Arduino's library manager under the old name `TGX`

I would like to change it to lowercase in order to have the main `#include <tgx.h>` matching the library's name as recommended by arduino's guidelines... 

Thanks !

**Comment by per1234** [comment]
Hi @vindar. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2024/10/10 14:49:29 Loaded 7358 libraries from DB
Removing TGX
Success!
```
