### ISSUE TITLE
Solicitud de actualización de la biblioteca Smelpro Macaron

### ISSUE THREAD

**Issue by ccencho** [arduino/library-registry#5340]
Hola, quisiera solicitar una actualización de mi biblioteca en el gestor de librerías de Arduino.

**Nombre de la biblioteca**: Smelpro Macaron
**Repositorio**: https://github.com/smelpro/Smelpro_Macaron
**Nueva versión etiquetada**: v1.0.1

He agregado nuevos ejercicios y realizado mejoras. Agradecería si pudieran actualizarla en el gestor de librerías.

**Comment by per1234** [comment]
Hi @ccencho. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager
