### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by D-314** [arduino/library-registry#5428]
### Library repository URL

https://github.com/D-314/IP2368-Arduino-Library

The functionality of the IP2366 and IP2368 libraries has been merged into a single library within this repository. To maintain consistency and avoid duplication, I request the following changes:

1. **Rename the current library** to reflect support for both IP2366 and IP2368 chips.
2. **Remove the separate IP2366 library**  from listing (https://github.com/arduino/library-registry/pull/5452), as its functionality is now fully integrated here.

**Comment by MatteoPologruto** [comment]
Done:
```
2024/11/26 14:55:38 Loaded 7504 libraries from DB
Removing IP2368
Success!
```
