### ISSUE TITLE
Add FireESP Library to Library Manager

### ISSUE THREAD

**Issue by Init-io** [arduino/library-registry#5453]
### **Description:**

Please add my library **FireEsp** to the Arduino Library Manager.

- **Library Name**: FireEsp  
- **GitHub Repository URL**: [https://github.com/Init-io/FireEsp](https://github.com/Init-io/FireEsp)  
- **Description**:  
  **FireESP** is an Arduino library designed for seamless integration of **ESP8266** and **ESP32** boards with **Firebase** services. It simplifies Firebase **Authentication** (sign-up, sign-in, email verification, password reset) and **Realtime Database** operations (store, update, retrieve, and delete data). FireESP ensures secure data transactions using `idToken` while also supporting Firebase's test mode for quick prototyping. With an intuitive API and robust functionality, FireESP is perfect for IoT applications and cloud-based projects.  

- **Version**: v1.0.1  

The library follows the Arduino Library Specification and is ready for review.  

Thank you!

**Comment by per1234** [comment]
Hi @Init-io. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
