### ISSUE TITLE
https://github.com/dac1e/RcSwitchReceiver to be added to arduino libraries.

### ISSUE THREAD

**Issue by dac1e** [arduino/library-registry#5467]
Please add https://github.com/dac1e/RcSwitchReceiver to arduino libaries.

Thank you.

**Comment by per1234** [comment]
Hi @dac1e. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

Regards, Per
