### ISSUE TITLE
Add FEETECH BUS Servo library for Arduino and ESP32

### ISSUE THREAD

**Issue by ftservo** [arduino/library-registry#5468]
Hi:)
Could you please add this library to the library manager?
https://github.com/ftservo/FTServo_Arduino

Thanks!

**Comment by per1234** [comment]
Hi @ftservo . We have a new system for submitting libraries. Please follow the instructions here:

https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Let me know if you have any questions.

Regards, Per
