### ISSUE TITLE
Unable to update version number, GitHub has completed, version update cannot be seen in Arduino Manager,

### ISSUE THREAD

**Issue by gooddisplayshare** [arduino/library-registry#5480]
The Arduino library version has been updated from v1.0.1 to v1.0.2. The library has been updated and the release version has been updated. However, the library manager in Arduino software is still v1.0.1. 
Could you please find the reason? Thank you~

https://github.com/gooddisplayshare/ESP32epd

**Comment by gooddisplayshare** [comment]
@per1234 ，When upgrading from version v1.0.1 to v1.0.2, all the work was carried out according to the instructions, including updating the version in the library. properties to v1.0.2 and creating v1.0.2 in the releases. But the Arduino library manager is still v1.0.1, do I need to do anything else?

**Comment by gooddisplayshare** [comment]
The error in my library has been fixed. The previous error version was 1.0.2. After fixing the error, does this version number need to be updated @per1234

**Comment by cmaglie** [comment]
The problem has been fixed, now the library manager is taking all the updates correctly.
