### ISSUE TITLE
Please, publish a new version of library to Library Manager

### ISSUE THREAD

**Issue by mhoseini967** [arduino/library-registry#558]
new version : 1.0.1
https://github.com/mhoseini967/AdvancedSevenSegment

**Comment by per1234** [comment]
Hi @mhoseini967. The Library Manager indexer checks all the libraries on the list for new tags/releases hourly and adds any new release that is compliant with the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time.

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there. In fact, your 1.0.1 release is already available for me:

![image](https://user-images.githubusercontent.com/8572152/135727885-baaca916-096b-4c9d-a9f4-81be1682a453.png)


We now provide a dedicated web page for each library that shows its indexer logs. You can see the logs for your library here:
http://downloads.arduino.cc/libraries/logs/github.com/mhoseini967/AdvancedSevenSegment/

Note that there is an important message in the logs about a bug in your library:
>Linting sketch in /home/ubuntu/workspace/gitclones/github.com/mhoseini967/AdvancedSevenSegment/examples/Demo
WARNING: Sketch file/folder name mismatch. The primary sketch file name must match the folder: Demo.ino. See:           
         https://arduino.github.io/arduino-cli/latest/sketch-specification/#primary-sketch-file (Rule SS001)
