### ISSUE TITLE
Having an issue with CelliesProjects/wm8978-esp32

### ISSUE THREAD

**Issue by CelliesProjects** [arduino/library-registry#593]
@per1234 
I am having issues updating https://github.com/CelliesProjects/wm8978-esp32 to a new version.

I don't see any log files at 
http://downloads.arduino.cc/libraries/logs/github.com/CelliesProjects/wm8978-esp32

**Comment by per1234** [comment]
Hi @CelliesProjects. The `wm8978-esp32` in the logs URL is actually a folder (the logs are in `index.html` under that path), so it's necessary to add a trailing slash to the URL:
http://downloads.arduino.cc/libraries/logs/github.com/CelliesProjects/wm8978-esp32/
With the URL fixed, the logs look just fine:
>2021/10/19 11:12:49 Scraping https://github.com/CelliesProjects/wm8978-esp32.git
2021/10/19 11:12:49 Checking out tag: 1.0.0
2021/10/19 11:12:49 Release wm8978-esp32:1.0.0 already loaded, skipping
2021/10/19 11:12:49 Checking out tag: 1.0.1
2021/10/19 11:12:49 Release wm8978-esp32:1.0.1 already loaded, skipping
2021/10/19 11:12:49 Checking out tag: 1.0.2
2021/10/19 11:12:49 Release wm8978-esp32:1.0.2 already loaded, skipping
2021/10/19 11:12:49 Checking out tag: 1.0.3
2021/10/19 11:12:49 Release wm8978-esp32:1.0.3 already loaded, skipping
2021/10/19 11:12:49 Checking out tag: 1.0.4
2021/10/19 11:12:49 Release wm8978-esp32:1.0.4 already loaded, skipping

and Library Manager too:
![image](https://user-images.githubusercontent.com/8572152/137900738-6ceeed50-1c32-4d4e-9a77-bceb57f57287.png)

So I think all is well. Please let me know if you have any questions or concerns.
