### ISSUE TITLE
Rename `CIE1931 Brightness Ramp` to `CIE1931`

### ISSUE THREAD

**Issue by nitz** [arduino/library-registry#627]
After adding v1.0.0, a lint warning mentioned that the name was beyond the recommended length and that it had spaces when it shouldn't, so I've shortened the name from `CIE1931 Brightness Ramp` to `CIE1931`.

Latest [lint](http://downloads.arduino.cc/libraries/logs/github.com/nitz/Cie1931/) already picked up the name change in tag v1.0.1, just need to change it on this end.

Thanks!

**Comment by per1234** [comment]
Hi @nitz. The requested change is now in progress: https://github.com/arduino/library-registry/pull/628.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. So you will get a notification from GitHub if you're subscribed to this issue.

After that, you can monitor the indexing of the library via its logs web page:

https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager
