### ISSUE TITLE
Please add library AVRTracing

### ISSUE THREAD

**Issue by ArminJo** [arduino/library-registry#630]
Hello,

I prepared an new Arduino compatible library.
https://github.com/ArminJo/AvrTracing

Could you add it to your list of libraries?

Thank you.
Armin

**Comment by per1234** [comment]
Hi @ArminJo. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

**Comment by ArminJo** [comment]
per1234 you are a genious! 🚀 
I love this way of reducing tedious effort. 👍 
Regards
Armin

**Comment by per1234** [comment]
Haha. I'm very glad to hear you like it!
