### ISSUE TITLE
[Library Manager] add Arduino_ICM20689

### ISSUE THREAD

**Issue by finani** [arduino/library-registry#638]
https://github.com/finani/Arduino_ICM20689

Hi, I made Arduino library for ICM-20689.
The library's name is Arduino_ICM20689 and tagged version is v1.0.0.

Please add this to Library manager.

Thank you in advance!

**Comment by per1234** [comment]
Hi @finani. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
