### ISSUE TITLE
[Library manager] EByte LoRa E22 library

### ISSUE THREAD

**Issue by xreef** [arduino/library-registry#641]
Source: https://github.com/xreef/EByte_LoRa_E22_Series_Library
Tag: https://github.com/xreef/EByte_LoRa_E22_Series_Library/releases/tag/v1.0.0

It's a complete library to interfacing EByte LoRa E22 device (from 4km to 10km)

Documentation
ENG: https://www.mischianti.org/category/my-libraries/ebyte-lora-e22-devices/
ITA: https://www.mischianti.org/it/category/le-mie-librerie/dispositivi-ebyte-lora-e22/

Bye Renzo

**Comment by per1234** [comment]
Hi @xreef. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
