### ISSUE TITLE
Request for library name change

### ISSUE THREAD

**Issue by siara-cc** [arduino/library-registry#65]
For this library: https://github.com/siara-cc/esp_arduino_sqlite3_lib,
is it possible to change the "name" of the library from "Sqlite3" to "Sqlite3 for ESP8266" in the Library Manager?
I have already changed the name in github to distinguish it from the ESP32 version.

**Comment by per1234** [comment]
OK, the name has now been changed.

FYI, we have just added a way for library maintainers to view the logs from the indexing of your library releases. The dedicated web page for this library is here:
https://downloads.arduino.cc/libraries/logs/github.com/siara-cc/esp_arduino_sqlite3_lib/
It is automatically updated every time the indexer job runs.
