### ISSUE TITLE
Remove Library from List 

### ISSUE THREAD

**Issue by TheFidax** [arduino/library-registry#656]
I would like to remove this library https://github.com/TheFidax/SusiOverI2c from the list as it is deprecated and replaced by a new one:  https://github.com/TheFidax/WireSusi

**Comment by per1234** [comment]
Hi @TheFidax. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

**Comment by rsora** [comment]
Engine maintenance done!
```
2021/12/17 17:45:43 Loaded 4447 libraries from DB
Removing SusiOverI2c
Success!
```
