### ISSUE TITLE
[Library Manager] Request to add E131 for SAMD based devices

### ISSUE THREAD

**Issue by arbourp** [arduino/library-registry#684]
Working with the Nano IoT 33 which is WiFi Enabled and based on SAMD architecture.

Would love to use a proper arduino rather than the ESP based devices that are always a puzzle.

**Comment by per1234** [comment]
Hi @arbourp. If you would like to submit a library to the Arduino Library Manager, follow the instructions here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
