### ISSUE TITLE
Rename request of 'The IoT Guru Integration' to 'IoTGuru'

### ISSUE THREAD

**Issue by gaborauth** [arduino/library-registry#709]
Hi,

We want to rename the library according to the Arduino Library lint rules:
```
WARNING: library.properties name value The IoT Guru integration is longer than the recommended length of 16 characters. (Rule LP010)                                                                                                   
WARNING: library.properties name The IoT Guru integration contains spaces. Although supported, best practices is to not use spaces. (Rule LP015)
```
The repository URL is https://github.com/IoTGuruLive/theiotguru-arduino-library
The renamed version is already released as v1.3.1 version.

Thanks,
Gábor AUTH

**Comment by per1234** [comment]
Hi @gaborauth. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by rsora** [comment]
Engine maintenance done!
```
2021/12/17 17:55:07 Loaded 4443 libraries from DB
Removing The IoT Guru integration
Success!
```
