### ISSUE TITLE
Rename request of 'modularCV' to 'controlVoltage'

### ISSUE THREAD

**Issue by ianhattwick** [arduino/library-registry#732]
I've renamed my modularCV library to 'controlVoltage', and would like to update this in the registry. 

The repository url is https://github.com/ianhattwick/controlVoltage

The current release has the updated name in library.properties

Thanks!

**Comment by per1234** [comment]
Hi @ianhattwick. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by rsora** [comment]
Engine maintenance done!
```
2021/12/17 17:53:36 Loaded 4444 libraries from DB
Removing modularCV
Success!
```
