### ISSUE TITLE
Rename request of "TwiLiquidCrytal by Arnakazim" to "TwiLiquidCrystal by Arnakazim"

### ISSUE THREAD

**Issue by arnakazim** [arduino/library-registry#738]
Hello,

The name of my library contained a small spelling error in the library.properties file. 

I renamed it with the correct spelling ("TwiLiquidCrystal by Arnakazim") and published a new release in the repository https://github.com/arnakazim/TwiLiquidCrystal-library.

Thank you!

**Comment by per1234** [comment]
Hi @arnakazim. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by rsora** [comment]
Engine maintenance done!
```
2021/12/17 17:49:35 Loaded 4446 libraries from DB
Removing TwiLiquidCrytal by Arnakazim
Success!
```
