### ISSUE TITLE
Add  Arduino-SerialDebugger library

### ISSUE THREAD

**Issue by xiaoming-sun6** [arduino/library-registry#792]
Hi :)
Could you please add this library to the library  manager?
https://github.com/xiaoming-sun6/Arduino-SerialDebugger

Thanks!

**Comment by per1234** [comment]
Hello @xiaoming-sun6. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.

**Comment by xiaoming-sun6** [comment]
OK, I got it.
Thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月15日(星期三) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [arduino/library-registry] Add  Arduino-SerialDebugger library (Issue #792)





 
Hello @xiaoming-sun6. We have a new system for submitting libraries. The instructions are here:
 https://github.com/arduino/library-registry#adding-a-library-to-library-manager
 
Please let me know if you have any questions.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
