### ISSUE TITLE
Update Library

### ISSUE THREAD

**Issue by oguzkaganyaglioglu** [arduino/library-registry#80]
I changed the author and maintainer name can you update the library
https://github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary

**Comment by per1234** [comment]
Hi @oguzkaganyaglioglu. I can see this is the information in the library metadata file:
https://github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary/blob/main/library.properties#L3-L4
```
author=Oguz Kagan
maintainer=Oguz Kagan <me@oguzkagan.xyz>
```

And this is the data in the Library Manager index:
http://downloads.arduino.cc/libraries/library_index.json
```json
{
  "name": "PLCustomDevices",
  "version": "0.1.0",
  "author": "Oguz Kagan",
  "maintainer": "Oguz Kagan \u003cme@oguzkagan.xyz\u003e",
```
So it looks like everything is up to date now.
