### ISSUE TITLE
[Library manager] Please add MyOwnBricks library

### ISSUE THREAD

**Issue by ysard** [arduino/library-registry#807]
Hi, Please add this new library to emulate Lego BOOST and PoweredUp devices.
https://github.com/ysard/MyOwnBricks

Thanks!

**Comment by per1234** [comment]
Hi @ysard. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
