### ISSUE TITLE
Remove Releases: Arancino@2.0.0 Arancino@1.4.2

### ISSUE THREAD

**Issue by artynet** [arduino/library-registry#887]
URL : https://github.com/smartmeio/arancino-library

please remove the v2.0.0 of our **Arancino** library since we had some issue with our CI/CD system and we are not ready to release the stable version yet. The git tag has already been removed as requested.

Kind Regards

**Comment by per1234** [comment]
Hi @artynet. Your request has been verified.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. You will get a notification from GitHub at that time if you're subscribed to this issue.

After that, you can monitor the indexing of the library via its logs web page:

https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by artynet** [comment]
thank you @per1234, can you give us an update about the current status of the request ? Thanks in advance.

**Comment by umbynos** [comment]
Backend job done:
```
2022/01/19 17:40:58 Loaded 4537 libraries from DB
Removing Arancino@2.0.0
Success!
```

**Comment by sergiotomasello** [comment]
@per1234 @umbynos unfortunately there were still problems in our CI/CD. But now they are solved. Could you please remove version 2.0.0 again and even 1.4.2.
Thank you very much

**Comment by per1234** [comment]
Hi @sergiotomasello. I have reopened the request and added `Arancino@1.4.2` to the list of releases to be removed on the next backend maintenance pass.

The maintainer will close this issue once your request has been completed.

**Comment by umbynos** [comment]
Backend job done:
```
2022/01/26 14:51:48 Loaded 4581 libraries from DB
Removing Arancino
Success!
```
