### ISSUE TITLE
[Library Manager] Please add SUSHI-EXP-BOARD-library

### ISSUE THREAD

**Issue by Kei0208** [arduino/library-registry#888]
Hello.

I created a library to manage my board named SUSHI-EXP-BOARD (that assembled with ESP32).
Could you add this to a list of libraries?

url: https://github.com/Kei0208/SUSHI-IO-EXP

Thanks.

**Comment by per1234** [comment]
Hi @Kei0208. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
