### ISSUE TITLE
[Feature request] Publicly reveal library downloads statistics

### ISSUE THREAD

**Issue by AlexIII** [arduino/library-registry#894]
It would really be nice to see library download stats, say like on npm.
It would be very informative to the lib devs and the users who choose among similar libraries.

**Comment by per1234** [comment]
Hi @AlexIII. Thanks for taking the time to request this important advancement.

I see we have another request for this at https://github.com/arduino/Arduino/issues/7265

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
