### ISSUE TITLE
Change repo name need a new PR?

### ISSUE THREAD

**Issue by lakshanthad** [arduino/library-registry#924]
Hello. I have already added a library to Arduino Library Manager and the library URL is available in repositories.txt. However, now I have renamed the repo. Do I need to PR again?

This is the library:
https://github.com/arduino/library-registry/blob/main/repositories.txt#L3322

Now the library URL after name change is this:
https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3

I can only see instructions on changing URL, but it is not a complete URL change. That is because the renaming of repo can still point to the new URL from the old URL.

Help would be appreciated!

Thank you.

**Comment by per1234** [comment]
Hi @lakshanthad.

>Do I need to PR again?

It is fine to make the request via an issue. I have submitted the necessary PR on your behalf.

>I can only see instructions on changing URL, but it is not a complete URL change. That is because the renaming of repo can still point to the new URL from the old URL.

Yes, GitHub will automatically redirect the old URL to the new one. However, it is safest not to rely on that redirect working forever, so it is best to update the URL.

The requested change is now in progress:

- https://github.com/arduino/library-registry/pull/925
- https://github.com/arduino/library-registry/pull/926

You are welcome to check the proposed change in that PR.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the PR linked above, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by lakshanthad** [comment]
Thank you very much for the clarification. Really appreciate it!

The proposed changes look good to me.

Thanks again.

**Comment by umbynos** [comment]
Solved in #926
