### ISSUE TITLE
Library Manager logs returning File Not Found

### ISSUE THREAD

**Issue by ewertons** [arduino/library-registry#928]
Dear Arduino developers,

I am trying to check the Library Manager logs of our library but the path returns File Not Found.

Is the link correct?
http://downloads.arduino.cc/libraries/logs/github.com/azure/azure-sdk-for-c-arduino 

Followed instructions in https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
Hi @ewertons. There were two problems with the URL you were using:

- Incorrect capitalization of [the organization name, "**A**zure"](https://github.com/Azure)
- Missing trailing slash (`/`)

Here are the logs:

https://downloads.arduino.cc/libraries/logs/github.com/Azure/azure-sdk-for-c-arduino/

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by ewertons** [comment]
Thank you very much, @per1234
