### ISSUE TITLE
Reflect name change of repo in library.properties on Arduino Library Manager

### ISSUE THREAD

**Issue by lakshanthad** [arduino/library-registry#929]
Hello,

The following repo is already added to Arduino Library Manager:
https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3

Here is the entry:
https://github.com/arduino/library-registry/blob/main/repositories.txt#L3323

However, when the last PR was done, the library name in **library.properties** was "Accelerometer And Gyroscope LSM6DS3"

Now the library name in **library.properties** is changed to "Seeed Arduino LSM6DS3"
https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3/blob/master/library.properties#L1

Can you help reflect this change in Arduino Library Manager?

Would appreciate the help!

**Comment by per1234** [comment]
Hi @lakshanthad. The requested change is now in progress: https://github.com/arduino/library-registry/pull/930

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by lakshanthad** [comment]
Thank you

**Comment by umbynos** [comment]
Solved in #930
