### ISSUE TITLE
Add library to Arduino library manager

### ISSUE THREAD

**Issue by sebmillet** [arduino/library-registry#93]
Hello

Could you please add the following libraries to Arduino Library Manager:

https://github.com/sebmillet/RF433any

and

https://github.com/sebmillet/DelayExec

Thanks,

Best Regards, Sébastien Millet

**Comment by per1234** [comment]
Hi @sebmillet. Thanks for your interest in contributing to the Arduino Library Manager index.

We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
