### ISSUE TITLE
Remove library "EdgeML"

### ISSUE THREAD

**Issue by tk-king** [arduino/library-registry#936]
https://github.com/edge-ml/arduino

Please remove all the releases of  our library "EdgeML" from the index. 
We already removed all the tags from the github repository.

Kind regards

**Comment by per1234** [comment]
Hi @tk-king. I need to understand the request more clearly before I can start that process.

The "remove library" in the issue title indicates that you would like the registration of the library removed entirely. This removes all releases from the index, but also removes the registration from the DB entirely, meaning that any new releases will not be indexed.

The "remove all releases from the index" request in the issue body is not necessarily the same thing as removing the library. If we only remove all the releases from the index, but leave the registration, then the indexer job will continue checking the repository for new tags and will add any new releases to the index.

Please tell me which of these two things you want.

**Comment by tk-king** [comment]
Hi @per1234. Sorry for my ambiguous wording.

I would like the registration of the library removed entirely. 

Kind regards

**Comment by per1234** [comment]
The requested change is now in progress @tk-king.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to this issue, you'll get a notification at that time.

**Comment by umbynos** [comment]
Done in #946
