### ISSUE TITLE
[Library Manager] Please add WiFiWire Library

### ISSUE THREAD

**Issue by chrmlinux** [arduino/library-registry#949]
Hello.

I created a library to manage my board named chrmlinux03
I think this will be a groundbreaking library
Use AsyncUDP to communicate I2C information with each other over WiFi
I don't think anyone has ever created it
Could you add this to a list of libraries?

url: https://github.com/chrmlinux/WiFiWire

Thanks.

**Comment by per1234** [comment]
Hi @chrmlinux. We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
