### ISSUE TITLE
[Library Manager] Please add library for CUBIC AM1008W-K I2C

### ISSUE THREAD

**Issue by neosarchizo** [arduino/library-registry#95]
github: https://github.com/neosarchizo/am1008w_k_i2c
release: https://github.com/neosarchizo/am1008w_k_i2c/releases/tag/1.0.0

Thanks!

**Comment by per1234** [comment]
Hi @neosarchizo. Thanks for your interest in contributing to the Arduino Library Manager index.

We have a new system for submitting libraries. The instructions are here:
https://github.com/arduino/library-registry#adding-a-library-to-library-manager

Please let me know if you have any questions.
