### ISSUE TITLE
[Library Manager] Please add tinyUDP

### ISSUE THREAD

**Issue by chrmlinux** [arduino/library-registry#985]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
https://github.com/chrmlinux/tinyUDP

**Comment by per1234** [comment]
Hi @chrmlinux. Please don't open issues for each library submission. I already explained the new process to you in https://github.com/arduino/library-registry/issues/949 and I see you successfully submitted it already https://github.com/arduino/library-registry/pull/982
